{
  "hash": "aa9869a412889068a047dc7f2ad66536",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 3: Spatio-Temporal Point Patterns Analysis\"\ndate: \"September 06, 2026\"\ndate-modified: \"last-modified\"\nformat: html\nexecute:\n  echo: true\n  eval: true\n  message: false\n  warning: false\n  freeze: true\neditor: visual\n---\n\n## 1 Overview\n\nA spatio-temporal point process (also called space-time or spatial-temporal point process) is a random collection of points, where each point represents the time and location of an event. Examples of events include incidence of disease, sightings or births of a species, or the occurrences of fires, earthquakes, lightning strikes, tsunamis, or volcanic eruptions.\n\nThe analysis of spatio-temporal point patterns is becoming increasingly necessary, given the rapid emergence of geographically and temporally indexed data in a wide range of fields. A range of methods for this type of analysis has been developed and implemented in R over the past decade, and this exercise draws on several of them.\n\nFor this exercise, forest fire events recorded in Kepulauan Bangka Belitung, Indonesia between 1 January 2023 and 31 December 2023 are used to illustrate the methods, procedures, and interpretations of spatio-temporal point pattern analysis.\n\n**Two specific questions guide this analysis:**\n\n- Do forest fire locations in Kepulauan Bangka Belitung show spatial and spatio-temporal independence?\n- If independence does not hold, where are the clusters concentrated, and during which periods do they occur?\n\n## 2 The Data\n\n| Dataset | Format | Source | Description |\n|------------------|------------------|------------------|------------------|\n| **forestfires** | CSV | [Fire Information for Resource Management System (FIRMS)](https://firms.modaps.eosdis.nasa.gov/download/) | Provides locations of forest fires detected by the Moderate Resolution Imaging Spectroradiometer (MODIS) sensor. Only fires within Kepulauan Bangka Belitung are retained for this exercise. |\n| **Kepulauan_Bangka_Belitung** | ESRI Shapefile | [Indonesia Geospasial](https://www.indonesia-geospasial.com/2023/05/download-shapefile-batas-administrasi.html) | Provides sub-district (*kelurahan*) boundaries of Kepulauan Bangka Belitung. The source data covers the whole of Indonesia; only sub-districts within Kepulauan Bangka Belitung are extracted for this exercise. |\n\n## 3 Installing and Loading R Packages\n\nSix R packages are used for this exercise:\n\n| Package | Purpose |\n|------------------------------------|------------------------------------|\n| [**sf**](https://r-spatial.github.io/sf/) | Imports, processes, and wrangles geospatial vector data |\n| [**spatstat**](https://cran.r-project.org/web/packages/spatstat/index.html) | Performs spatial point pattern analysis, including cross-type functions such as *Kcross()* and *Lcross()* |\n| [**sparr**](https://tilmandavies.github.io/sparr/index.html) | Estimates fixed and adaptive kernel-smoothed spatial relative risk surfaces via the density-ratio method, performs subsequent inference, and supports fixed-bandwidth spatio-temporal density and relative risk estimation |\n| [**stpp**](https://cran.r-project.org/web/packages/stpp/index.html) | Simulates, plots, and analyses spatio-temporal point patterns, including the space-time K-function used later in this exercise |\n| [**tmap**](https://r-tmap.github.io/tmap/) | Produces cartographic-quality thematic maps |\n| [**tidyverse**](https://www.tidyverse.org/) | A collection of packages supporting common data science tasks, including data import, transformation, wrangling, and visualisation |\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spatstat, sparr, \n               stpp, tmap, tidyverse)\n```\n:::\n\n\n## 4 Importing and Preparing Study Area\n\n### 4.1 Importing Study Area\n\nThe study area boundary for **Kepulauan Bangka Belitung** is imported using `st_read()`. The nationwide sub-district boundary shapefile is imported, and `glimpse()` is used to inspect its attribute table structure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_raw <- st_read(dsn = \"data/BATAS WILAYAH KELURAHAN-DESA 10K\",\n                    layer = \"Batas_Wilayah_KelurahanDesa_10K_AR\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Batas_Wilayah_KelurahanDesa_10K_AR' from data source \n  `C:\\yxlinn\\ISSS626-GAA\\Hands-on_Ex\\Hands-on_Ex03\\data\\BATAS WILAYAH KELURAHAN-DESA 10K' \n  using driver `ESRI Shapefile'\nSimple feature collection with 83518 features and 26 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 94.97191 ymin: -11.00762 xmax: 141.02 ymax: 6.076832\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check the attribute table structure\nglimpse(kbb_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 83,518\nColumns: 27\n$ OBJECTID <dbl> 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1…\n$ NAMOBJ   <chr> \"Cidadap\", \"Cidadap\", \"Cidahu\", \"Cidatar\", \"Cidolog\", \"Ciduga…\n$ FCODE    <chr> \"BA03070040\", \"BA03070040\", \"BA03070040\", \"BA03070040\", \"BA03…\n$ REMARK   <chr> \"Wilayah Administrasi Kelurahan/Desa\", \"Wilayah Administrasi …\n$ METADATA <chr> \"TASWIL1000020221227_DATA_BATAS_DESAKELURAHAN\", \"TASWIL100002…\n$ SRS_ID   <chr> \"SRGI 2013\", \"SRGI 2013\", \"SRGI 2013\", \"SRGI 2013\", \"SRGI 201…\n$ KDBBPS   <chr> \"3202\", \"3202\", \"3202\", \"32.05\", \"3202\", NA, NA, \"32.05\", \"32…\n$ KDCBPS   <chr> \"3202081\", \"3202111\", \"3202031\", \"32.05.160\", \"3202070\", NA, …\n$ KDCPUM   <chr> \"32.02.44\", \"32.02.02\", \"32.02.25\", \"32.05.20\", \"32.02.43\", \"…\n$ KDEBPS   <chr> \"3202081002\", \"3202111004\", \"3202031001\", \"32.05.160.2002\", \"…\n$ KDEPUM   <chr> \"32.02.44.2002\", \"32.02.02.2001\", \"32.02.25.2004\", \"32.05.20.…\n$ KDPBPS   <chr> \"32\", \"32\", \"32\", \"32\", \"32\", NA, NA, \"32\", \"32\", \"32\", NA, \"…\n$ KDPKAB   <chr> \"32.02\", \"32.02\", \"32.02\", \"32.05\", \"32.02\", \"32.06\", \"32.10\"…\n$ KDPPUM   <chr> \"32\", \"32\", \"32\", \"32\", \"32\", \"32\", \"32\", \"32\", \"32\", \"32\", \"…\n$ LUASWH   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ TIPADM   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1…\n$ WADMKC   <chr> \"Cidadap\", \"Simpenan\", \"Cibitung\", \"Cisurupan\", \"Cidolog\", \"C…\n$ WADMKD   <chr> \"Cidadap\", \"Cidadap\", \"Cidahu\", \"Cidatar\", \"Cidolog\", \"Ciduga…\n$ WADMKK   <chr> \"Sukabumi\", \"Sukabumi\", \"Sukabumi\", \"Garut\", \"Sukabumi\", \"Tas…\n$ WADMPR   <chr> \"Jawa Barat\", \"Jawa Barat\", \"Jawa Barat\", \"Jawa Barat\", \"Jawa…\n$ WIADKC   <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ WIADKK   <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ WIADPR   <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ WIADKD   <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ UUPP     <chr> \"Hasil Delineasi Batas Desa 2017\", \"Hasil Delineasi Batas Des…\n$ LUAS     <dbl> 19.465373, 11.956814, 28.248993, 2.742905, 21.720740, 14.2843…\n$ geometry <MULTIPOLYGON [°]> MULTIPOLYGON (((106.9755 -7..., MULTIPOLYGON (((…\n```\n\n\n:::\n:::\n\n\nThe `WADMPR` column is identified as the province field, and `unique()` is used to confirm the exact string used for Kepulauan Bangka Belitung.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(kbb_raw$WADMPR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Jawa Barat\"                 \"Bali\"                      \n [3] \"Nusa Tenggara Barat\"        \"Jawa Tengah\"               \n [5] \"Daerah Istimewa Yogyakarta\" \"Jawa Timur\"                \n [7] \"Sulawesi Selatan\"           \"Sumatera Barat\"            \n [9] \"Jambi\"                      \"Lampung\"                   \n[11] \"Sumatera Selatan\"           \"Bengkulu\"                  \n[13] \"Banten\"                     \"Kepulauan Bangka Belitung\" \n[15] \"DKI Jakarta\"                \"Kalimantan Selatan\"        \n[17] \"Kalimantan Barat\"           \"Kalimantan Tengah\"         \n[19] \"Nusa Tenggara Timur\"        \"Maluku\"                    \n[21] \"Papua Selatan\"              \"Sulawesi Barat\"            \n[23] \"Papua Tengah\"               \"Papua Pegunungan\"          \n[25] \"Papua Barat\"                \"Papua\"                     \n[27] \"Sulawesi Tengah\"            \"Sulawesi Tenggara\"         \n[29] \"Kepulauan Riau\"             \"Riau\"                      \n[31] \"Sumatera Utara\"             \"Kalimantan Timur\"          \n[33] \"Kalimantan Utara\"           \"Sulawesi Utara\"            \n[35] \"Aceh\"                       NA                          \n[37] \"Maluku Utara\"               \"Papua Barat Daya\"          \n[39] \"Gorontalo\"                 \n```\n\n\n:::\n:::\n\n\nThe dataset is filtered to retain only sub-districts within Kepulauan Bangka Belitung, and the result is plotted to visually confirm that the correct study area was extracted.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_sf <- kbb_raw %>%\n  filter(WADMPR == \"Kepulauan Bangka Belitung\")\n\nplot(st_geometry(kbb_sf))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe filtered dataset is then exported as a standalone shapefile, keeping the study area self-contained and independent of the raw source file.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_write(kbb_sf,\n         dsn = \"data\",\n         layer = \"Kepulauan_Bangka_Belitung\",\n         driver = \"ESRI Shapefile\",\n         delete_layer = TRUE)\n```\n:::\n\n\nThe filtered **Kepulauan_Bangka_Belitung** shapefile is imported into the R environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_sf <- st_read(dsn = \"data\", \n                  layer = \"Kepulauan_Bangka_Belitung\") %>%\n  st_union() %>%\n  st_zm(drop = TRUE, what = \"ZM\") %>%\n  st_transform(crs = 32748)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Kepulauan_Bangka_Belitung' from data source \n  `C:\\yxlinn\\ISSS626-GAA\\Hands-on_Ex\\Hands-on_Ex03\\data' using driver `ESRI Shapefile'\nSimple feature collection with 393 features and 26 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 105.1085 ymin: -3.80161 xmax: 108.8718 ymax: -1.493399\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n::: callout-note\nThe coordinate reference system used here is EPSG:32748 (WGS 84 / UTM zone 48S), the appropriate projected CRS for Kepulauan Bangka Belitung's location in Indonesia.\n:::\n\n### 4.2 Converting to owin\n\nNext, `as.owin()` converts the prepared boundary into an **owin** object, which is the spatial window format required by **spatstat** for point pattern analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_owin <- as.owin(kbb_sf)\nkbb_owin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwindow: polygonal boundary\nenclosing rectangle: [512066.8, 930756.9] x [9579205, 9834915] units\n```\n\n\n:::\n:::\n\n\n`class()` is used to confirm that the output is an **owin** object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(kbb_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"owin\"\n```\n\n\n:::\n:::\n\n\n## 5 Importing and Preparing the Forest Fire Data\n\nThe forest fire dataset is imported, and `glimpse()` is used to inspect its column names and data types before any processing is applied.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_raw <- read_csv(\"data/forestfires.csv\")\nglimpse(fire_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 53,128\nColumns: 15\n$ latitude   <dbl> -0.9296, -1.3048, -4.0833, -2.9122, -2.7533, -2.7547, -2.51…\n$ longitude  <dbl> 101.7016, 101.8272, 122.5457, 121.1542, 121.7388, 121.7294,…\n$ brightness <dbl> 310.0, 318.6, 309.8, 312.8, 310.4, 344.8, 307.8, 326.8, 311…\n$ scan       <dbl> 1.5, 1.5, 1.1, 1.0, 1.1, 1.1, 1.0, 1.0, 1.0, 1.0, 1.5, 1.0,…\n$ track      <dbl> 1.2, 1.2, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.2, 1.0,…\n$ acq_date   <date> 2023-01-01, 2023-01-01, 2023-01-02, 2023-01-02, 2023-01-02…\n$ acq_time   <chr> \"0640\", \"0640\", \"0543\", \"0543\", \"0543\", \"0543\", \"0543\", \"05…\n$ satellite  <chr> \"Aqua\", \"Aqua\", \"Aqua\", \"Aqua\", \"Aqua\", \"Aqua\", \"Aqua\", \"Aq…\n$ instrument <chr> \"MODIS\", \"MODIS\", \"MODIS\", \"MODIS\", \"MODIS\", \"MODIS\", \"MODI…\n$ confidence <dbl> 21, 66, 59, 63, 47, 93, 38, 83, 66, 54, 61, 40, 69, 84, 65,…\n$ version    <dbl> 61.03, 61.03, 61.03, 61.03, 61.03, 61.03, 61.03, 61.03, 61.…\n$ bright_t31 <dbl> 271.1, 276.7, 276.0, 294.9, 294.4, 296.3, 285.7, 287.1, 286…\n$ frp        <dbl> 16.2, 27.5, 7.3, 6.7, 4.6, 50.1, 4.0, 20.7, 6.5, 10.6, 9.0,…\n$ daynight   <chr> \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\",…\n$ type       <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0,…\n```\n\n\n:::\n:::\n\n\nThe fire data is converted into an sf object using `st_as_sf()`, reprojected to EPSG:32748 using `st_transform()` (matching the coordinate reference system used for the study area boundary), then filtered to retain only fire points falling within the Kepulauan Bangka Belitung boundary using `st_filter()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- fire_raw %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326) %>%\n  st_transform(crs = 32748) %>%\n  st_filter(kbb_sf)\n```\n:::\n\n\n::: callout-note\nThe forest fire data was downloaded for the whole of Indonesia (53,128 records spanning multiple islands), so `st_filter()` is included here to retain only fire points within the study area.\n:::\n\nAs spatstat's point pattern objects require numeric marks instead of date objects, three time-based fields are derived from acq_date using mutate():\n\n- **DayOfYear** (the numeric day of the year, 1–365)\n- **Month_num** (the calendar month as a number, 1–12)\n- **Month_fac** (the calendar month as a labeled factor, e.g. \"January\")\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- fire_sf %>%\n  mutate(DayOfYear = yday(acq_date),\n         Month_num = month(acq_date),\n         Month_fac = month(acq_date, label = TRUE, abbr = FALSE))\n```\n:::\n\n\n## 6 Visualising the Fire Points\n\n### 6.1 Overall Plot\n\nAn overall map is prepared to visualise the spatial distribution of all forest fire events in Kepulauan Bangka Belitung, Indonesia for 2023.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf) +\n  tm_polygons() +\ntm_shape(fire_sf) +\n  tm_dots()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n### 6.2 Visualising Geographic Distribution of Forest Fires By Month\n\nThe maps below show the monthly geographic distribution of forest fires across Kepulauan Bangka Belitung.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf)+\n  tm_polygons() +\ntm_shape(fire_sf) +\n  tm_dots(size = 0.2, fill = \"red\") +\ntm_facets(by=\"Month_fac\", \n          free.coords = FALSE, \n          drop.units = TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\nThe pattern reflected is consistent with Indonesia's known dry season and fire cycle. The country's dry season typically spans from around April to October, with fire activity peaking between August and October. 2023 was especially severe, marking Indonesia's worst fire season since 2019, driven by an intense El Nino event that dried out vegetation nationwide. Since burning in Indonesia is more commonly linked to agricultural land clearing than to natural causes, the July to October spike observed here likely reflects both the seasonal dry conditions and land-clearing activity concentrated during that period.\n:::\n\n## 7 Computing STKDE by Month\n\nThis section covers STKDE computation using [spattemp.density()](https://tilmandavies.github.io/sparr/reference/spattemp.density.html) from **sparr**.\n\n### 7.1 Extracting Forest Fires by Month\n\nSince `as.ppp()` only requires the mark field and geometry field from the input sf data frame, unwanted columns are removed, retaining only `Month_num`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month <- fire_sf %>%\n  select(Month_num)\n```\n:::\n\n\n### 7.2 Creating the ppp object\n\n`as.ppp()` converts fire_month into a marked planar point pattern object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_ppp <- as.ppp(fire_month)\nfire_month_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 905 points\nmarks are numeric, of storage type  'double'\nwindow: rectangle = [521564.1, 862416.4] x [9642001, 9828767] units\n```\n\n\n:::\n:::\n\n\nThe code below is used to confirm the object's structure and check for anything unexpected.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fire_month_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  905 points\nAverage intensity 1.421623e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   8.000   9.000   8.644  10.000  12.000 \n\nWindow: rectangle = [521564.1, 862416.4] x [9642001, 9828767] units\n                    (340900 x 186800 units)\nWindow area = 63659700000 square units\n```\n\n\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\nFrom the above summary, it shows a mean of 8.644, indicating that the average fire event occurred slightly later in the year. This is consistent with the earlier monthly facet maps, where fire activity was concentrated in the July to October period, pulling the mean upward.\n:::\n\nNext, `any(duplicated())` checks if there are any duplicated point events:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(duplicated(fire_month_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n### 7.3 Including the owin object\n\n`fire_month_ppp` is combined with the `kbb_owin` study area boundary, restricting the point pattern to the actual province outline:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_owin <- fire_month_ppp[kbb_owin]\nsummary(fire_month_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  905 points\nAverage intensity 5.421272e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   8.000   9.000   8.644  10.000  12.000 \n\nWindow: polygonal boundary\n536 separate polygons (no holes)\n             vertices        area relative.area\npolygon 1         224 1.44169e+04      8.64e-07\npolygon 2       47493 1.15336e+10      6.91e-01\npolygon 3          37 5.13028e+03      3.07e-07\npolygon 4         240 5.22392e+04      3.13e-06\npolygon 5         183 9.02576e+03      5.41e-07\npolygon 6         132 4.85115e+03      2.91e-07\npolygon 7          50 5.88594e+03      3.53e-07\npolygon 8         127 1.76573e+04      1.06e-06\npolygon 9          11 8.26759e+02      4.95e-08\npolygon 10         69 1.55459e+03      9.31e-08\npolygon 11        299 5.20975e+03      3.12e-07\npolygon 12        112 2.22941e+04      1.34e-06\npolygon 13        364 9.31571e+03      5.58e-07\npolygon 14         36 4.06692e+03      2.44e-07\npolygon 15        108 1.14359e+04      6.85e-07\npolygon 16        140 7.82064e+03      4.68e-07\npolygon 17         88 7.60683e+02      4.56e-08\npolygon 18         41 1.22996e+03      7.37e-08\npolygon 19        153 2.27681e+04      1.36e-06\npolygon 20        104 8.01630e+03      4.80e-07\npolygon 21         82 5.16578e+02      3.09e-08\npolygon 22         68 6.68868e+03      4.01e-07\npolygon 23         47 2.02532e+03      1.21e-07\npolygon 24         97 9.76825e+02      5.85e-08\npolygon 25         30 1.63452e+02      9.79e-09\npolygon 26         37 2.87532e+02      1.72e-08\npolygon 27         52 3.34365e+02      2.00e-08\npolygon 28         40 1.08564e+02      6.50e-09\npolygon 29         15 3.75707e+02      2.25e-08\npolygon 30        253 9.89301e+04      5.93e-06\npolygon 31         56 9.83747e+03      5.89e-07\npolygon 32        103 1.04940e+05      6.29e-06\npolygon 33        128 4.92781e+03      2.95e-07\npolygon 34         75 1.71034e+03      1.02e-07\npolygon 35        176 1.71303e+04      1.03e-06\npolygon 36        930 1.20433e+05      7.21e-06\npolygon 37         14 6.27189e+02      3.76e-08\npolygon 38        229 4.45273e+04      2.67e-06\npolygon 39        271 8.13480e+03      4.87e-07\npolygon 40         32 3.31713e+03      1.99e-07\npolygon 41         23 1.36780e+03      8.19e-08\npolygon 42        160 1.79143e+04      1.07e-06\npolygon 43         58 9.97284e+02      5.97e-08\npolygon 44        132 2.92557e+03      1.75e-07\npolygon 45         66 8.51878e+02      5.10e-08\npolygon 46        101 2.91536e+03      1.75e-07\npolygon 47        364 1.17646e+04      7.05e-07\npolygon 48        207 2.75963e+04      1.65e-06\npolygon 49        503 2.41199e+04      1.44e-06\npolygon 50         53 2.89637e+02      1.74e-08\npolygon 51         33 5.47341e+02      3.28e-08\npolygon 52        148 1.31977e+04      7.91e-07\npolygon 53        123 2.20905e+03      1.32e-07\npolygon 54        172 3.73641e+03      2.24e-07\npolygon 55         37 3.03851e+02      1.82e-08\npolygon 56         27 2.44109e+03      1.46e-07\npolygon 57        361 1.02640e+04      6.15e-07\npolygon 58         21 1.39685e+03      8.37e-08\npolygon 59        293 4.08808e+03      2.45e-07\npolygon 60         21 2.36831e+03      1.42e-07\npolygon 61        138 2.33177e+04      1.40e-06\npolygon 62        129 4.27432e+04      2.56e-06\npolygon 63         64 3.01600e+03      1.81e-07\npolygon 64         47 1.19948e+02      7.19e-09\npolygon 65         62 1.81736e+04      1.09e-06\npolygon 66        182 5.12222e+04      3.07e-06\npolygon 67         24 6.25240e+03      3.75e-07\npolygon 68         83 6.16929e+04      3.70e-06\npolygon 69        208 1.32015e+05      7.91e-06\npolygon 70        245 6.01676e+03      3.60e-07\npolygon 71         24 1.61122e+03      9.65e-08\npolygon 72         40 5.87229e+03      3.52e-07\npolygon 73         22 7.15173e+03      4.28e-07\npolygon 74         39 5.62880e+03      3.37e-07\npolygon 75         60 1.62047e+04      9.71e-07\npolygon 76         53 9.99251e+04      5.99e-06\npolygon 77         29 2.72926e+03      1.63e-07\npolygon 78         33 5.18519e+03      3.11e-07\npolygon 79         25 1.50389e+04      9.01e-07\npolygon 80         41 2.69836e+04      1.62e-06\npolygon 81        113 1.25165e+05      7.50e-06\npolygon 82        334 3.09456e+04      1.85e-06\npolygon 83        207 5.35038e+03      3.21e-07\npolygon 84        176 4.40524e+03      2.64e-07\npolygon 85         34 3.89900e+04      2.34e-06\npolygon 86         52 5.43138e+04      3.25e-06\npolygon 87         75 3.19877e+05      1.92e-05\npolygon 88        256 3.06427e+05      1.84e-05\npolygon 89         32 3.70857e+03      2.22e-07\npolygon 90         23 3.74160e+03      2.24e-07\npolygon 91         39 1.72621e+05      1.03e-05\npolygon 92         92 1.29311e+06      7.75e-05\npolygon 93         16 1.05235e+03      6.30e-08\npolygon 94         72 1.38351e+05      8.29e-06\npolygon 95         34 3.95205e+04      2.37e-06\npolygon 96         25 5.37634e+04      3.22e-06\npolygon 97         25 6.54682e+02      3.92e-08\npolygon 98         13 1.11052e+03      6.65e-08\npolygon 99         36 1.53995e+04      9.22e-07\npolygon 100        30 3.57280e+02      2.14e-08\npolygon 101       165 1.14502e+05      6.86e-06\npolygon 102        47 1.19091e+04      7.13e-07\npolygon 103       118 6.60980e+04      3.96e-06\npolygon 104       300 9.67862e+05      5.80e-05\npolygon 105       263 1.32479e+05      7.94e-06\npolygon 106        25 2.83922e+03      1.70e-07\npolygon 107        99 1.96748e+03      1.18e-07\npolygon 108        86 6.21856e+02      3.73e-08\npolygon 109        98 1.14843e+03      6.88e-08\npolygon 110        61 1.31593e+04      7.88e-07\npolygon 111       429 3.77216e+04      2.26e-06\npolygon 112        44 1.98461e+04      1.19e-06\npolygon 113       203 1.26109e+04      7.55e-07\npolygon 114        23 1.04369e+04      6.25e-07\npolygon 115       145 7.61645e+03      4.56e-07\npolygon 116        24 1.44462e+04      8.65e-07\npolygon 117        36 2.93121e+05      1.76e-05\npolygon 118        35 2.12545e+05      1.27e-05\npolygon 119       143 9.54504e+04      5.72e-06\npolygon 120        25 5.69171e+03      3.41e-07\npolygon 121        24 9.42429e+03      5.65e-07\npolygon 122       154 1.78950e+05      1.07e-05\npolygon 123        20 4.79029e+03      2.87e-07\npolygon 124      1106 3.11656e+06      1.87e-04\npolygon 125       382 2.09352e+06      1.25e-04\npolygon 126        12 5.89819e+03      3.53e-07\npolygon 127        39 6.59978e+03      3.95e-07\npolygon 128        29 3.30953e+03      1.98e-07\npolygon 129        12 5.55436e+02      3.33e-08\npolygon 130        10 6.79524e+03      4.07e-07\npolygon 131       110 2.43449e+06      1.46e-04\npolygon 132        60 7.75343e+04      4.64e-06\npolygon 133        33 2.16720e+05      1.30e-05\npolygon 134        23 3.74579e+04      2.24e-06\npolygon 135        28 1.40794e+05      8.43e-06\npolygon 136        25 1.18674e+05      7.11e-06\npolygon 137       167 2.33168e+04      1.40e-06\npolygon 138        48 2.24641e+04      1.35e-06\npolygon 139     30751 4.61643e+09      2.77e-01\npolygon 140        26 2.48498e+05      1.49e-05\npolygon 141       157 4.76604e+03      2.86e-07\npolygon 142       158 1.31489e+05      7.88e-06\npolygon 143       377 1.07590e+04      6.45e-07\npolygon 144        43 3.61058e+03      2.16e-07\npolygon 145        41 2.38706e+03      1.43e-07\npolygon 146        73 2.46292e+04      1.48e-06\npolygon 147       257 3.77901e+03      2.26e-07\npolygon 148        20 1.90750e+02      1.14e-08\npolygon 149      1012 4.40490e+04      2.64e-06\npolygon 150        37 7.41999e+03      4.44e-07\npolygon 151       150 8.32584e+03      4.99e-07\npolygon 152       367 8.56158e+03      5.13e-07\npolygon 153        86 2.47026e+03      1.48e-07\npolygon 154       369 1.49521e+06      8.96e-05\npolygon 155       455 2.05782e+04      1.23e-06\npolygon 156       545 1.85709e+04      1.11e-06\npolygon 157        26 9.82309e+04      5.88e-06\npolygon 158        23 6.24600e+04      3.74e-06\npolygon 159        80 1.85926e+05      1.11e-05\npolygon 160       181 1.00867e+04      6.04e-07\npolygon 161         9 4.66269e+02      2.79e-08\npolygon 162        12 1.57226e+03      9.42e-08\npolygon 163      1370 1.62014e+05      9.71e-06\npolygon 164       147 4.27698e+03      2.56e-07\npolygon 165        17 6.78403e+02      4.06e-08\npolygon 166       174 4.50684e+03      2.70e-07\npolygon 167        22 1.00911e+03      6.04e-08\npolygon 168       505 9.32104e+03      5.58e-07\npolygon 169       388 2.38186e+04      1.43e-06\npolygon 170       268 9.26439e+03      5.55e-07\npolygon 171       187 5.91498e+03      3.54e-07\npolygon 172        27 5.21572e+02      3.12e-08\npolygon 173        73 5.79342e+04      3.47e-06\npolygon 174         8 3.45142e+02      2.07e-08\npolygon 175       264 4.69271e+03      2.81e-07\npolygon 176        13 1.68585e+03      1.01e-07\npolygon 177        12 1.73856e+03      1.04e-07\npolygon 178        38 8.21441e+04      4.92e-06\npolygon 179       165 2.88093e+03      1.73e-07\npolygon 180        30 5.27851e+03      3.16e-07\npolygon 181       184 2.78886e+03      1.67e-07\npolygon 182       115 1.02564e+04      6.14e-07\npolygon 183       825 6.35817e+04      3.81e-06\npolygon 184        22 3.43522e+04      2.06e-06\npolygon 185        37 2.90142e+04      1.74e-06\npolygon 186      1343 1.31687e+05      7.89e-06\npolygon 187       158 1.18094e+06      7.07e-05\npolygon 188        26 2.17630e+04      1.30e-06\npolygon 189        44 6.87830e+04      4.12e-06\npolygon 190        25 3.09938e+04      1.86e-06\npolygon 191        23 1.55547e+04      9.32e-07\npolygon 192        19 1.09125e+04      6.54e-07\npolygon 193        73 1.55665e+05      9.32e-06\npolygon 194        16 2.07355e+03      1.24e-07\npolygon 195       118 1.78404e+03      1.07e-07\npolygon 196       103 3.52167e+05      2.11e-05\npolygon 197        23 7.84829e+04      4.70e-06\npolygon 198        78 4.59370e+04      2.75e-06\npolygon 199        23 4.71418e+03      2.82e-07\npolygon 200       264 5.02201e+03      3.01e-07\npolygon 201       124 1.76285e+03      1.06e-07\npolygon 202       289 5.74196e+03      3.44e-07\npolygon 203        26 1.76569e+03      1.06e-07\npolygon 204       411 2.16333e+06      1.30e-04\npolygon 205        18 2.40346e+03      1.44e-07\npolygon 206        31 5.66328e+03      3.39e-07\npolygon 207       302 1.02351e+04      6.13e-07\npolygon 208        49 1.75107e+04      1.05e-06\npolygon 209       174 3.25924e+03      1.95e-07\npolygon 210       273 9.21060e+03      5.52e-07\npolygon 211        33 2.48011e+04      1.49e-06\npolygon 212        37 3.18189e+03      1.91e-07\npolygon 213       185 2.88575e+03      1.73e-07\npolygon 214        14 9.36783e+02      5.61e-08\npolygon 215        41 6.74413e+03      4.04e-07\npolygon 216        13 5.77083e+02      3.46e-08\npolygon 217        39 4.07815e+03      2.44e-07\npolygon 218        28 2.80868e+03      1.68e-07\npolygon 219        16 1.72867e+03      1.04e-07\npolygon 220        91 2.03446e+05      1.22e-05\npolygon 221        30 5.15545e+03      3.09e-07\npolygon 222        30 1.21375e+04      7.27e-07\npolygon 223        22 3.23230e+03      1.94e-07\npolygon 224       181 5.47327e+05      3.28e-05\npolygon 225        23 4.61412e+03      2.76e-07\npolygon 226        26 4.93257e+03      2.95e-07\npolygon 227        80 1.77114e+05      1.06e-05\npolygon 228        50 1.43320e+04      8.59e-07\npolygon 229        35 5.63291e+04      3.37e-06\npolygon 230        43 1.06830e+05      6.40e-06\npolygon 231        51 7.90324e+04      4.73e-06\npolygon 232        27 8.01152e+04      4.80e-06\npolygon 233        25 7.49167e+03      4.49e-07\npolygon 234        38 5.25674e+03      3.15e-07\npolygon 235        22 6.99628e+03      4.19e-07\npolygon 236        23 6.97525e+03      4.18e-07\npolygon 237        31 1.01012e+04      6.05e-07\npolygon 238        61 2.17522e+04      1.30e-06\npolygon 239        79 7.53691e+05      4.51e-05\npolygon 240        25 2.99755e+04      1.80e-06\npolygon 241        29 6.85309e+03      4.11e-07\npolygon 242        31 2.11732e+03      1.27e-07\npolygon 243        63 1.93154e+03      1.16e-07\npolygon 244        70 7.52041e+03      4.50e-07\npolygon 245         9 1.86134e+03      1.12e-07\npolygon 246        48 7.92413e+04      4.75e-06\npolygon 247        54 9.77639e+03      5.86e-07\npolygon 248        10 1.93540e+04      1.16e-06\npolygon 249        34 2.85845e+04      1.71e-06\npolygon 250        44 6.63946e+02      3.98e-08\npolygon 251        17 2.23524e+04      1.34e-06\npolygon 252        19 4.90841e+03      2.94e-07\npolygon 253        53 3.48865e+04      2.09e-06\npolygon 254        28 1.09995e+04      6.59e-07\npolygon 255         8 2.55600e+03      1.53e-07\npolygon 256        29 7.65133e+03      4.58e-07\npolygon 257        21 1.41298e+05      8.46e-06\npolygon 258        97 3.05805e+04      1.83e-06\npolygon 259        30 4.94313e+03      2.96e-07\npolygon 260       178 2.41168e+04      1.44e-06\npolygon 261        14 1.86688e+03      1.12e-07\npolygon 262        83 6.80491e+03      4.08e-07\npolygon 263       126 2.05545e+04      1.23e-06\npolygon 264        21 1.33354e+03      7.99e-08\npolygon 265       139 3.20608e+05      1.92e-05\npolygon 266        36 1.50019e+04      8.99e-07\npolygon 267        75 1.10838e+05      6.64e-06\npolygon 268        36 1.96382e+03      1.18e-07\npolygon 269        33 6.27656e+03      3.76e-07\npolygon 270        15 5.78645e+03      3.47e-07\npolygon 271        10 6.24812e+03      3.74e-07\npolygon 272      1032 1.67625e+07      1.00e-03\npolygon 273        16 4.50507e+03      2.70e-07\npolygon 274        51 2.32616e+04      1.39e-06\npolygon 275        18 1.51856e+04      9.10e-07\npolygon 276        98 1.57468e+05      9.43e-06\npolygon 277        14 4.58094e+03      2.74e-07\npolygon 278        22 5.23183e+03      3.13e-07\npolygon 279       231 7.48261e+04      4.48e-06\npolygon 280        17 3.13434e+03      1.88e-07\npolygon 281        18 6.41884e+03      3.85e-07\npolygon 282      3490 4.80502e+07      2.88e-03\npolygon 283      2677 1.19161e+08      7.14e-03\npolygon 284       472 3.37686e+06      2.02e-04\npolygon 285        16 4.51755e+03      2.71e-07\npolygon 286        86 7.10284e+04      4.25e-06\npolygon 287        31 1.06751e+04      6.39e-07\npolygon 288       272 1.62573e+06      9.74e-05\npolygon 289        46 5.15929e+04      3.09e-06\npolygon 290        13 1.18371e+04      7.09e-07\npolygon 291       107 1.07570e+05      6.44e-06\npolygon 292        73 5.79175e+04      3.47e-06\npolygon 293       290 3.84739e+06      2.30e-04\npolygon 294        11 9.78833e+02      5.86e-08\npolygon 295        17 2.15656e+03      1.29e-07\npolygon 296       501 3.43058e+06      2.06e-04\npolygon 297        33 2.80296e+04      1.68e-06\npolygon 298        39 1.40795e+04      8.43e-07\npolygon 299       160 2.12311e+05      1.27e-05\npolygon 300        47 4.13611e+03      2.48e-07\npolygon 301        31 1.91654e+04      1.15e-06\npolygon 302       794 7.28888e+06      4.37e-04\npolygon 303        28 5.95476e+03      3.57e-07\npolygon 304       148 1.47839e+05      8.86e-06\npolygon 305        28 1.39147e+04      8.34e-07\npolygon 306        52 9.07175e+03      5.43e-07\npolygon 307       102 3.22900e+04      1.93e-06\npolygon 308        21 6.55158e+03      3.92e-07\npolygon 309        13 7.96291e+03      4.77e-07\npolygon 310       235 2.19662e+06      1.32e-04\npolygon 311        49 3.32353e+04      1.99e-06\npolygon 312      3013 2.11761e+08      1.27e-02\npolygon 313        25 6.12931e+03      3.67e-07\npolygon 314        13 1.29657e+03      7.77e-08\npolygon 315        47 2.23896e+05      1.34e-05\npolygon 316        26 6.56360e+03      3.93e-07\npolygon 317        37 1.70858e+04      1.02e-06\npolygon 318        44 6.63087e+03      3.97e-07\npolygon 319        33 1.34250e+04      8.04e-07\npolygon 320       240 1.51037e+06      9.05e-05\npolygon 321        20 3.64277e+03      2.18e-07\npolygon 322        36 1.11851e+04      6.70e-07\npolygon 323        25 1.52203e+04      9.12e-07\npolygon 324      1458 2.22187e+07      1.33e-03\npolygon 325        25 1.06985e+04      6.41e-07\npolygon 326        42 4.37545e+04      2.62e-06\npolygon 327       435 2.35126e+06      1.41e-04\npolygon 328        40 4.75423e+04      2.85e-06\npolygon 329        19 5.08404e+03      3.05e-07\npolygon 330        53 5.46624e+04      3.27e-06\npolygon 331        36 3.00997e+04      1.80e-06\npolygon 332        24 1.57036e+04      9.41e-07\npolygon 333        23 1.35063e+04      8.09e-07\npolygon 334       293 1.14361e+06      6.85e-05\npolygon 335       203 4.34268e+05      2.60e-05\npolygon 336       141 3.73920e+05      2.24e-05\npolygon 337       357 1.20495e+06      7.22e-05\npolygon 338       174 4.77564e+05      2.86e-05\npolygon 339        79 6.88812e+04      4.13e-06\npolygon 340       702 5.20138e+06      3.12e-04\npolygon 341        17 9.99224e+02      5.99e-08\npolygon 342        70 5.87205e+04      3.52e-06\npolygon 343       457 1.78149e+06      1.07e-04\npolygon 344        42 4.19918e+04      2.52e-06\npolygon 345        21 5.33572e+03      3.20e-07\npolygon 346       485 3.15582e+06      1.89e-04\npolygon 347        75 2.04007e+05      1.22e-05\npolygon 348        84 3.48205e+04      2.09e-06\npolygon 349        72 1.72000e+05      1.03e-05\npolygon 350        41 3.05345e+04      1.83e-06\npolygon 351        19 1.19066e+03      7.13e-08\npolygon 352        23 1.14404e+04      6.85e-07\npolygon 353        42 4.25092e+04      2.55e-06\npolygon 354       522 1.29468e+06      7.76e-05\npolygon 355        72 1.56162e+05      9.35e-06\npolygon 356        39 2.31954e+04      1.39e-06\npolygon 357       337 1.69623e+06      1.02e-04\npolygon 358        26 8.69952e+02      5.21e-08\npolygon 359        60 5.55180e+03      3.33e-07\npolygon 360        71 1.18527e+05      7.10e-06\npolygon 361        52 4.79365e+04      2.87e-06\npolygon 362        23 1.46380e+03      8.77e-08\npolygon 363       152 7.26594e+05      4.35e-05\npolygon 364       336 1.04565e+06      6.26e-05\npolygon 365       369 3.83501e+06      2.30e-04\npolygon 366        23 1.35323e+03      8.11e-08\npolygon 367        14 9.44061e+02      5.66e-08\npolygon 368        20 1.19878e+03      7.18e-08\npolygon 369        20 1.22479e+03      7.34e-08\npolygon 370        12 3.14266e+02      1.88e-08\npolygon 371        96 5.74385e+05      3.44e-05\npolygon 372        16 1.47565e+03      8.84e-08\npolygon 373        11 3.37925e+02      2.02e-08\npolygon 374        28 1.20121e+04      7.20e-07\npolygon 375        18 5.11103e+03      3.06e-07\npolygon 376        30 4.15479e+03      2.49e-07\npolygon 377        19 1.44435e+03      8.65e-08\npolygon 378       257 8.82441e+05      5.29e-05\npolygon 379        17 1.40023e+03      8.39e-08\npolygon 380       190 4.78248e+05      2.86e-05\npolygon 381        25 7.73598e+03      4.63e-07\npolygon 382        72 1.55476e+04      9.31e-07\npolygon 383       707 7.43557e+06      4.45e-04\npolygon 384        91 2.54866e+05      1.53e-05\npolygon 385        64 1.03791e+05      6.22e-06\npolygon 386        14 3.56320e+03      2.13e-07\npolygon 387        71 4.83339e+04      2.90e-06\npolygon 388        17 4.75969e+03      2.85e-07\npolygon 389        18 3.58794e+03      2.15e-07\npolygon 390        31 1.65116e+04      9.89e-07\npolygon 391       102 6.27945e+04      3.76e-06\npolygon 392       127 3.73709e+05      2.24e-05\npolygon 393        22 8.17944e+02      4.90e-08\npolygon 394        20 1.23038e+03      7.37e-08\npolygon 395        83 1.55106e+03      9.29e-08\npolygon 396        20 2.32477e+03      1.39e-07\npolygon 397        35 1.36281e+04      8.16e-07\npolygon 398        38 1.64553e+04      9.86e-07\npolygon 399        39 1.01099e+04      6.06e-07\npolygon 400        50 9.42394e+02      5.65e-08\npolygon 401        63 3.44429e+03      2.06e-07\npolygon 402        16 9.61725e+02      5.76e-08\npolygon 403        20 5.47059e+03      3.28e-07\npolygon 404        24 1.12657e+04      6.75e-07\npolygon 405        25 3.23022e+03      1.94e-07\npolygon 406        26 8.94640e+03      5.36e-07\npolygon 407        20 5.05672e+03      3.03e-07\npolygon 408        14 5.21025e+02      3.12e-08\npolygon 409        68 3.42268e+03      2.05e-07\npolygon 410        23 4.53694e+03      2.72e-07\npolygon 411        45 1.87962e+03      1.13e-07\npolygon 412        18 1.50333e+03      9.01e-08\npolygon 413        18 3.10345e+03      1.86e-07\npolygon 414        10 5.35745e+02      3.21e-08\npolygon 415        21 3.63596e+03      2.18e-07\npolygon 416        13 1.02116e+03      6.12e-08\npolygon 417        12 1.73619e+03      1.04e-07\npolygon 418        23 7.61461e+03      4.56e-07\npolygon 419        19 4.49103e+03      2.69e-07\npolygon 420       711 3.82473e+06      2.29e-04\npolygon 421        15 1.38213e+03      8.28e-08\npolygon 422        17 5.43121e+03      3.25e-07\npolygon 423        21 1.97955e+03      1.19e-07\npolygon 424        22 1.66783e+03      9.99e-08\npolygon 425        15 7.33146e+02      4.39e-08\npolygon 426        39 4.29024e+04      2.57e-06\npolygon 427        24 2.68164e+03      1.61e-07\npolygon 428        25 2.98281e+03      1.79e-07\npolygon 429        30 4.40393e+03      2.64e-07\npolygon 430        14 7.05851e+02      4.23e-08\npolygon 431        11 6.69535e+02      4.01e-08\npolygon 432        14 6.42130e+02      3.85e-08\npolygon 433        15 6.02994e+02      3.61e-08\npolygon 434        11 5.50154e+02      3.30e-08\npolygon 435       117 4.46868e+05      2.68e-05\npolygon 436        28 1.31455e+04      7.87e-07\npolygon 437        24 6.53420e+03      3.91e-07\npolygon 438        95 3.16866e+04      1.90e-06\npolygon 439        68 7.41846e+03      4.44e-07\npolygon 440        20 1.57643e+03      9.44e-08\npolygon 441       297 4.65582e+05      2.79e-05\npolygon 442       108 8.38877e+04      5.03e-06\npolygon 443        90 2.65369e+05      1.59e-05\npolygon 444         6 2.47451e+02      1.48e-08\npolygon 445        63 8.35521e+03      5.01e-07\npolygon 446       114 5.16535e+04      3.09e-06\npolygon 447       389 1.08583e+06      6.50e-05\npolygon 448       391 7.99345e+05      4.79e-05\npolygon 449       136 1.63759e+05      9.81e-06\npolygon 450        50 6.32478e+04      3.79e-06\npolygon 451       219 2.54243e+05      1.52e-05\npolygon 452        53 6.25631e+04      3.75e-06\npolygon 453       278 2.66230e+05      1.59e-05\npolygon 454        38 2.90336e+03      1.74e-07\npolygon 455        26 2.48467e+03      1.49e-07\npolygon 456        41 6.89351e+03      4.13e-07\npolygon 457       299 4.00812e+05      2.40e-05\npolygon 458      1030 1.66243e+07      9.96e-04\npolygon 459        34 2.32389e+03      1.39e-07\npolygon 460        32 1.87841e+03      1.13e-07\npolygon 461        37 9.87386e+02      5.91e-08\npolygon 462       682 1.39226e+06      8.34e-05\npolygon 463        34 2.62560e+03      1.57e-07\npolygon 464        12 1.10550e+02      6.62e-09\npolygon 465        18 1.38831e+02      8.32e-09\npolygon 466        10 5.53120e+01      3.31e-09\npolygon 467        26 2.25004e+02      1.35e-08\npolygon 468        28 2.92620e+03      1.75e-07\npolygon 469       283 2.23929e+06      1.34e-04\npolygon 470        16 8.29282e+02      4.97e-08\npolygon 471        26 1.57985e+03      9.46e-08\npolygon 472       623 1.20943e+06      7.24e-05\npolygon 473        14 1.98308e+02      1.19e-08\npolygon 474        18 7.87079e+02      4.71e-08\npolygon 475        66 2.55809e+04      1.53e-06\npolygon 476        69 2.17800e+04      1.30e-06\npolygon 477        91 2.73187e+04      1.64e-06\npolygon 478        43 2.82278e+04      1.69e-06\npolygon 479        19 1.18992e+04      7.13e-07\npolygon 480        22 1.17190e+04      7.02e-07\npolygon 481        34 1.47055e+04      8.81e-07\npolygon 482        62 2.24563e+04      1.35e-06\npolygon 483        78 8.48842e+04      5.08e-06\npolygon 484        46 1.35989e+04      8.15e-07\npolygon 485         7 2.14611e+02      1.29e-08\npolygon 486        28 1.98540e+03      1.19e-07\npolygon 487        22 1.08368e+04      6.49e-07\npolygon 488        19 9.47042e+03      5.67e-07\npolygon 489         5 3.42089e+02      2.05e-08\npolygon 490        31 1.44650e+03      8.67e-08\npolygon 491         8 3.61796e+02      2.17e-08\npolygon 492         7 1.78403e+02      1.07e-08\npolygon 493        12 4.86579e+02      2.91e-08\npolygon 494         9 6.30641e+02      3.78e-08\npolygon 495       343 5.45240e+05      3.27e-05\npolygon 496       111 6.42841e+04      3.85e-06\npolygon 497        26 2.61765e+04      1.57e-06\npolygon 498         5 6.79484e+02      4.07e-08\npolygon 499         7 6.50446e+02      3.90e-08\npolygon 500       423 3.18233e+06      1.91e-04\npolygon 501        79 2.49961e+04      1.50e-06\npolygon 502        54 1.22067e+05      7.31e-06\npolygon 503        80 3.18143e+04      1.91e-06\npolygon 504        22 4.25083e+02      2.55e-08\npolygon 505        30 3.18447e+03      1.91e-07\npolygon 506        90 1.82111e+05      1.09e-05\npolygon 507        31 2.44090e+03      1.46e-07\npolygon 508        28 2.89515e+04      1.73e-06\npolygon 509        24 2.01142e+03      1.20e-07\npolygon 510        36 8.22704e+03      4.93e-07\npolygon 511        17 2.57702e+03      1.54e-07\npolygon 512         8 5.23581e+01      3.14e-09\npolygon 513        12 4.38046e+02      2.62e-08\npolygon 514        51 1.03129e+04      6.18e-07\npolygon 515       136 2.52678e+04      1.51e-06\npolygon 516        42 1.93188e+04      1.16e-06\npolygon 517        52 3.22341e+04      1.93e-06\npolygon 518        38 6.80476e+03      4.08e-07\npolygon 519        21 1.11895e+03      6.70e-08\npolygon 520        35 1.81671e+03      1.09e-07\npolygon 521       400 1.88255e+06      1.13e-04\npolygon 522        56 2.91054e+04      1.74e-06\npolygon 523       353 9.08138e+05      5.44e-05\npolygon 524        24 4.07068e+03      2.44e-07\npolygon 525       160 1.73580e+05      1.04e-05\npolygon 526       171 2.86639e+05      1.72e-05\npolygon 527       116 2.13804e+05      1.28e-05\npolygon 528        85 6.98799e+04      4.19e-06\npolygon 529       393 1.08414e+06      6.49e-05\npolygon 530        41 9.36420e+03      5.61e-07\npolygon 531        56 9.26379e+04      5.55e-06\npolygon 532       125 1.99837e+05      1.20e-05\npolygon 533        45 1.22254e+04      7.32e-07\npolygon 534        40 1.08040e+05      6.47e-06\npolygon 535         8 6.19200e+03      3.71e-07\npolygon 536         9 2.71560e+04      1.63e-06\nenclosing rectangle: [512066.8, 930756.9] x [9579205, 9834915] units\n                     (418700 x 255700 units)\nWindow area = 16693500000 square units\nFraction of frame area: 0.156\n```\n\n\n:::\n:::\n\n\n::: callout-note\nThe window consists of **536 separate polygons** instead of one connected polygon because Kepulauan Bangka Belitung is an archipelago. Its two main islands, Bangka and Belitung, along with many smaller surrounding islands, are all separated by open sea and do not share a land border. *st_union()* can only merge polygons that physically touch, so each island stays as its own separate piece within the combined boundary.\n:::\n\nThe result is plotted to confirm the point pattern is correctly bounded by the study area.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fire_month_owin)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-19-1.png){width=768}\n:::\n:::\n\n\n### 7.4 Computing Spatio-temporal KDE\n\n`spattemp.density()` from **sparr** is used to compute the STKDE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_kde <- spattemp.density(fire_month_owin)\nsummary(st_kde)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 19110 (spatial)\n  lambda = 0.0264 (temporal)\n\nNo. of observations\n  905 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 930756.9] x [9579205, 9834915]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [2.515909e-36, 6.317034e-10]\n```\n\n\n:::\n:::\n\n\n### 7.5 Plotting the Spatio-temporal KDE Object\n\nThe code below is used to visualise the KDE surfaces from July to December 2023:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(7,8,9,10,11,12)\npar(mfcol=c(2,3))\nfor(i in tims){\n  plot(st_kde, i,\n       override.par=FALSE,\n       fix.range=TRUE,\n       main=paste(\"KDE at month\",i))\n}\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-21-1.png){width=960}\n:::\n:::\n\n\nThe KDE surfaces show a clear intensification and decline across the second half of 2023. July and August show moderate density concentrated on Bangka Island's western side, appearing as a purple-to-pink hotspot. This intensifies sharply in September, then peaks in October, where the hotspot turns bright orange-to-yellow, indicating the highest estimated fire density of any month shown. By November, the hotspot has faded back toward purple/blue, and December shows minimal density across the entire study area.\n\nBelitung Island and the surrounding smaller islands generally show low density across the six months, though September and October show a modest increase. This indicates fire activity in 2023 was concentrated mainly on Bangka Island, with Belitung experiencing comparatively minor fire activity during the same period.\n\n::: callout-note\n**Analysis:**\n\nOctober stands out as the single most intense month, consistent with the July to October fire season pattern identified in the earlier monthly forest fire maps.\n:::\n\n## 8 Computing STKDE by Day of Year\n\nThis section covers computing STKDE using fire occurrence by day of year instead of by month.\n\n### 8.1 Extracting Forest Fires by Day of Year\n\nUnwanted columns are removed from the fire point data, retaining only `DayOfYear`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_yday <- fire_sf %>%\n  select(DayOfYear)\n```\n:::\n\n\n### 8.2 Creating the ppp object\n\n`as.ppp()` converts fire_yday into a marked planar point pattern object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_yday_ppp <- as.ppp(fire_yday)\nfire_yday_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 905 points\nmarks are numeric, of storage type  'double'\nwindow: rectangle = [521564.1, 862416.4] x [9642001, 9828767] units\n```\n\n\n:::\n:::\n\n\n### 8.3 Including the owin object\n\nThe ppp object is combined with the `kbb_owin` study area boundary:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_yday_owin <- fire_yday_ppp[kbb_owin]\nsummary(fire_yday_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  905 points\nAverage intensity 5.421272e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   10.0   220.0   258.0   247.8   288.0   360.0 \n\nWindow: polygonal boundary\n536 separate polygons (no holes)\n             vertices        area relative.area\npolygon 1         224 1.44169e+04      8.64e-07\npolygon 2       47493 1.15336e+10      6.91e-01\npolygon 3          37 5.13028e+03      3.07e-07\npolygon 4         240 5.22392e+04      3.13e-06\npolygon 5         183 9.02576e+03      5.41e-07\npolygon 6         132 4.85115e+03      2.91e-07\npolygon 7          50 5.88594e+03      3.53e-07\npolygon 8         127 1.76573e+04      1.06e-06\npolygon 9          11 8.26759e+02      4.95e-08\npolygon 10         69 1.55459e+03      9.31e-08\npolygon 11        299 5.20975e+03      3.12e-07\npolygon 12        112 2.22941e+04      1.34e-06\npolygon 13        364 9.31571e+03      5.58e-07\npolygon 14         36 4.06692e+03      2.44e-07\npolygon 15        108 1.14359e+04      6.85e-07\npolygon 16        140 7.82064e+03      4.68e-07\npolygon 17         88 7.60683e+02      4.56e-08\npolygon 18         41 1.22996e+03      7.37e-08\npolygon 19        153 2.27681e+04      1.36e-06\npolygon 20        104 8.01630e+03      4.80e-07\npolygon 21         82 5.16578e+02      3.09e-08\npolygon 22         68 6.68868e+03      4.01e-07\npolygon 23         47 2.02532e+03      1.21e-07\npolygon 24         97 9.76825e+02      5.85e-08\npolygon 25         30 1.63452e+02      9.79e-09\npolygon 26         37 2.87532e+02      1.72e-08\npolygon 27         52 3.34365e+02      2.00e-08\npolygon 28         40 1.08564e+02      6.50e-09\npolygon 29         15 3.75707e+02      2.25e-08\npolygon 30        253 9.89301e+04      5.93e-06\npolygon 31         56 9.83747e+03      5.89e-07\npolygon 32        103 1.04940e+05      6.29e-06\npolygon 33        128 4.92781e+03      2.95e-07\npolygon 34         75 1.71034e+03      1.02e-07\npolygon 35        176 1.71303e+04      1.03e-06\npolygon 36        930 1.20433e+05      7.21e-06\npolygon 37         14 6.27189e+02      3.76e-08\npolygon 38        229 4.45273e+04      2.67e-06\npolygon 39        271 8.13480e+03      4.87e-07\npolygon 40         32 3.31713e+03      1.99e-07\npolygon 41         23 1.36780e+03      8.19e-08\npolygon 42        160 1.79143e+04      1.07e-06\npolygon 43         58 9.97284e+02      5.97e-08\npolygon 44        132 2.92557e+03      1.75e-07\npolygon 45         66 8.51878e+02      5.10e-08\npolygon 46        101 2.91536e+03      1.75e-07\npolygon 47        364 1.17646e+04      7.05e-07\npolygon 48        207 2.75963e+04      1.65e-06\npolygon 49        503 2.41199e+04      1.44e-06\npolygon 50         53 2.89637e+02      1.74e-08\npolygon 51         33 5.47341e+02      3.28e-08\npolygon 52        148 1.31977e+04      7.91e-07\npolygon 53        123 2.20905e+03      1.32e-07\npolygon 54        172 3.73641e+03      2.24e-07\npolygon 55         37 3.03851e+02      1.82e-08\npolygon 56         27 2.44109e+03      1.46e-07\npolygon 57        361 1.02640e+04      6.15e-07\npolygon 58         21 1.39685e+03      8.37e-08\npolygon 59        293 4.08808e+03      2.45e-07\npolygon 60         21 2.36831e+03      1.42e-07\npolygon 61        138 2.33177e+04      1.40e-06\npolygon 62        129 4.27432e+04      2.56e-06\npolygon 63         64 3.01600e+03      1.81e-07\npolygon 64         47 1.19948e+02      7.19e-09\npolygon 65         62 1.81736e+04      1.09e-06\npolygon 66        182 5.12222e+04      3.07e-06\npolygon 67         24 6.25240e+03      3.75e-07\npolygon 68         83 6.16929e+04      3.70e-06\npolygon 69        208 1.32015e+05      7.91e-06\npolygon 70        245 6.01676e+03      3.60e-07\npolygon 71         24 1.61122e+03      9.65e-08\npolygon 72         40 5.87229e+03      3.52e-07\npolygon 73         22 7.15173e+03      4.28e-07\npolygon 74         39 5.62880e+03      3.37e-07\npolygon 75         60 1.62047e+04      9.71e-07\npolygon 76         53 9.99251e+04      5.99e-06\npolygon 77         29 2.72926e+03      1.63e-07\npolygon 78         33 5.18519e+03      3.11e-07\npolygon 79         25 1.50389e+04      9.01e-07\npolygon 80         41 2.69836e+04      1.62e-06\npolygon 81        113 1.25165e+05      7.50e-06\npolygon 82        334 3.09456e+04      1.85e-06\npolygon 83        207 5.35038e+03      3.21e-07\npolygon 84        176 4.40524e+03      2.64e-07\npolygon 85         34 3.89900e+04      2.34e-06\npolygon 86         52 5.43138e+04      3.25e-06\npolygon 87         75 3.19877e+05      1.92e-05\npolygon 88        256 3.06427e+05      1.84e-05\npolygon 89         32 3.70857e+03      2.22e-07\npolygon 90         23 3.74160e+03      2.24e-07\npolygon 91         39 1.72621e+05      1.03e-05\npolygon 92         92 1.29311e+06      7.75e-05\npolygon 93         16 1.05235e+03      6.30e-08\npolygon 94         72 1.38351e+05      8.29e-06\npolygon 95         34 3.95205e+04      2.37e-06\npolygon 96         25 5.37634e+04      3.22e-06\npolygon 97         25 6.54682e+02      3.92e-08\npolygon 98         13 1.11052e+03      6.65e-08\npolygon 99         36 1.53995e+04      9.22e-07\npolygon 100        30 3.57280e+02      2.14e-08\npolygon 101       165 1.14502e+05      6.86e-06\npolygon 102        47 1.19091e+04      7.13e-07\npolygon 103       118 6.60980e+04      3.96e-06\npolygon 104       300 9.67862e+05      5.80e-05\npolygon 105       263 1.32479e+05      7.94e-06\npolygon 106        25 2.83922e+03      1.70e-07\npolygon 107        99 1.96748e+03      1.18e-07\npolygon 108        86 6.21856e+02      3.73e-08\npolygon 109        98 1.14843e+03      6.88e-08\npolygon 110        61 1.31593e+04      7.88e-07\npolygon 111       429 3.77216e+04      2.26e-06\npolygon 112        44 1.98461e+04      1.19e-06\npolygon 113       203 1.26109e+04      7.55e-07\npolygon 114        23 1.04369e+04      6.25e-07\npolygon 115       145 7.61645e+03      4.56e-07\npolygon 116        24 1.44462e+04      8.65e-07\npolygon 117        36 2.93121e+05      1.76e-05\npolygon 118        35 2.12545e+05      1.27e-05\npolygon 119       143 9.54504e+04      5.72e-06\npolygon 120        25 5.69171e+03      3.41e-07\npolygon 121        24 9.42429e+03      5.65e-07\npolygon 122       154 1.78950e+05      1.07e-05\npolygon 123        20 4.79029e+03      2.87e-07\npolygon 124      1106 3.11656e+06      1.87e-04\npolygon 125       382 2.09352e+06      1.25e-04\npolygon 126        12 5.89819e+03      3.53e-07\npolygon 127        39 6.59978e+03      3.95e-07\npolygon 128        29 3.30953e+03      1.98e-07\npolygon 129        12 5.55436e+02      3.33e-08\npolygon 130        10 6.79524e+03      4.07e-07\npolygon 131       110 2.43449e+06      1.46e-04\npolygon 132        60 7.75343e+04      4.64e-06\npolygon 133        33 2.16720e+05      1.30e-05\npolygon 134        23 3.74579e+04      2.24e-06\npolygon 135        28 1.40794e+05      8.43e-06\npolygon 136        25 1.18674e+05      7.11e-06\npolygon 137       167 2.33168e+04      1.40e-06\npolygon 138        48 2.24641e+04      1.35e-06\npolygon 139     30751 4.61643e+09      2.77e-01\npolygon 140        26 2.48498e+05      1.49e-05\npolygon 141       157 4.76604e+03      2.86e-07\npolygon 142       158 1.31489e+05      7.88e-06\npolygon 143       377 1.07590e+04      6.45e-07\npolygon 144        43 3.61058e+03      2.16e-07\npolygon 145        41 2.38706e+03      1.43e-07\npolygon 146        73 2.46292e+04      1.48e-06\npolygon 147       257 3.77901e+03      2.26e-07\npolygon 148        20 1.90750e+02      1.14e-08\npolygon 149      1012 4.40490e+04      2.64e-06\npolygon 150        37 7.41999e+03      4.44e-07\npolygon 151       150 8.32584e+03      4.99e-07\npolygon 152       367 8.56158e+03      5.13e-07\npolygon 153        86 2.47026e+03      1.48e-07\npolygon 154       369 1.49521e+06      8.96e-05\npolygon 155       455 2.05782e+04      1.23e-06\npolygon 156       545 1.85709e+04      1.11e-06\npolygon 157        26 9.82309e+04      5.88e-06\npolygon 158        23 6.24600e+04      3.74e-06\npolygon 159        80 1.85926e+05      1.11e-05\npolygon 160       181 1.00867e+04      6.04e-07\npolygon 161         9 4.66269e+02      2.79e-08\npolygon 162        12 1.57226e+03      9.42e-08\npolygon 163      1370 1.62014e+05      9.71e-06\npolygon 164       147 4.27698e+03      2.56e-07\npolygon 165        17 6.78403e+02      4.06e-08\npolygon 166       174 4.50684e+03      2.70e-07\npolygon 167        22 1.00911e+03      6.04e-08\npolygon 168       505 9.32104e+03      5.58e-07\npolygon 169       388 2.38186e+04      1.43e-06\npolygon 170       268 9.26439e+03      5.55e-07\npolygon 171       187 5.91498e+03      3.54e-07\npolygon 172        27 5.21572e+02      3.12e-08\npolygon 173        73 5.79342e+04      3.47e-06\npolygon 174         8 3.45142e+02      2.07e-08\npolygon 175       264 4.69271e+03      2.81e-07\npolygon 176        13 1.68585e+03      1.01e-07\npolygon 177        12 1.73856e+03      1.04e-07\npolygon 178        38 8.21441e+04      4.92e-06\npolygon 179       165 2.88093e+03      1.73e-07\npolygon 180        30 5.27851e+03      3.16e-07\npolygon 181       184 2.78886e+03      1.67e-07\npolygon 182       115 1.02564e+04      6.14e-07\npolygon 183       825 6.35817e+04      3.81e-06\npolygon 184        22 3.43522e+04      2.06e-06\npolygon 185        37 2.90142e+04      1.74e-06\npolygon 186      1343 1.31687e+05      7.89e-06\npolygon 187       158 1.18094e+06      7.07e-05\npolygon 188        26 2.17630e+04      1.30e-06\npolygon 189        44 6.87830e+04      4.12e-06\npolygon 190        25 3.09938e+04      1.86e-06\npolygon 191        23 1.55547e+04      9.32e-07\npolygon 192        19 1.09125e+04      6.54e-07\npolygon 193        73 1.55665e+05      9.32e-06\npolygon 194        16 2.07355e+03      1.24e-07\npolygon 195       118 1.78404e+03      1.07e-07\npolygon 196       103 3.52167e+05      2.11e-05\npolygon 197        23 7.84829e+04      4.70e-06\npolygon 198        78 4.59370e+04      2.75e-06\npolygon 199        23 4.71418e+03      2.82e-07\npolygon 200       264 5.02201e+03      3.01e-07\npolygon 201       124 1.76285e+03      1.06e-07\npolygon 202       289 5.74196e+03      3.44e-07\npolygon 203        26 1.76569e+03      1.06e-07\npolygon 204       411 2.16333e+06      1.30e-04\npolygon 205        18 2.40346e+03      1.44e-07\npolygon 206        31 5.66328e+03      3.39e-07\npolygon 207       302 1.02351e+04      6.13e-07\npolygon 208        49 1.75107e+04      1.05e-06\npolygon 209       174 3.25924e+03      1.95e-07\npolygon 210       273 9.21060e+03      5.52e-07\npolygon 211        33 2.48011e+04      1.49e-06\npolygon 212        37 3.18189e+03      1.91e-07\npolygon 213       185 2.88575e+03      1.73e-07\npolygon 214        14 9.36783e+02      5.61e-08\npolygon 215        41 6.74413e+03      4.04e-07\npolygon 216        13 5.77083e+02      3.46e-08\npolygon 217        39 4.07815e+03      2.44e-07\npolygon 218        28 2.80868e+03      1.68e-07\npolygon 219        16 1.72867e+03      1.04e-07\npolygon 220        91 2.03446e+05      1.22e-05\npolygon 221        30 5.15545e+03      3.09e-07\npolygon 222        30 1.21375e+04      7.27e-07\npolygon 223        22 3.23230e+03      1.94e-07\npolygon 224       181 5.47327e+05      3.28e-05\npolygon 225        23 4.61412e+03      2.76e-07\npolygon 226        26 4.93257e+03      2.95e-07\npolygon 227        80 1.77114e+05      1.06e-05\npolygon 228        50 1.43320e+04      8.59e-07\npolygon 229        35 5.63291e+04      3.37e-06\npolygon 230        43 1.06830e+05      6.40e-06\npolygon 231        51 7.90324e+04      4.73e-06\npolygon 232        27 8.01152e+04      4.80e-06\npolygon 233        25 7.49167e+03      4.49e-07\npolygon 234        38 5.25674e+03      3.15e-07\npolygon 235        22 6.99628e+03      4.19e-07\npolygon 236        23 6.97525e+03      4.18e-07\npolygon 237        31 1.01012e+04      6.05e-07\npolygon 238        61 2.17522e+04      1.30e-06\npolygon 239        79 7.53691e+05      4.51e-05\npolygon 240        25 2.99755e+04      1.80e-06\npolygon 241        29 6.85309e+03      4.11e-07\npolygon 242        31 2.11732e+03      1.27e-07\npolygon 243        63 1.93154e+03      1.16e-07\npolygon 244        70 7.52041e+03      4.50e-07\npolygon 245         9 1.86134e+03      1.12e-07\npolygon 246        48 7.92413e+04      4.75e-06\npolygon 247        54 9.77639e+03      5.86e-07\npolygon 248        10 1.93540e+04      1.16e-06\npolygon 249        34 2.85845e+04      1.71e-06\npolygon 250        44 6.63946e+02      3.98e-08\npolygon 251        17 2.23524e+04      1.34e-06\npolygon 252        19 4.90841e+03      2.94e-07\npolygon 253        53 3.48865e+04      2.09e-06\npolygon 254        28 1.09995e+04      6.59e-07\npolygon 255         8 2.55600e+03      1.53e-07\npolygon 256        29 7.65133e+03      4.58e-07\npolygon 257        21 1.41298e+05      8.46e-06\npolygon 258        97 3.05805e+04      1.83e-06\npolygon 259        30 4.94313e+03      2.96e-07\npolygon 260       178 2.41168e+04      1.44e-06\npolygon 261        14 1.86688e+03      1.12e-07\npolygon 262        83 6.80491e+03      4.08e-07\npolygon 263       126 2.05545e+04      1.23e-06\npolygon 264        21 1.33354e+03      7.99e-08\npolygon 265       139 3.20608e+05      1.92e-05\npolygon 266        36 1.50019e+04      8.99e-07\npolygon 267        75 1.10838e+05      6.64e-06\npolygon 268        36 1.96382e+03      1.18e-07\npolygon 269        33 6.27656e+03      3.76e-07\npolygon 270        15 5.78645e+03      3.47e-07\npolygon 271        10 6.24812e+03      3.74e-07\npolygon 272      1032 1.67625e+07      1.00e-03\npolygon 273        16 4.50507e+03      2.70e-07\npolygon 274        51 2.32616e+04      1.39e-06\npolygon 275        18 1.51856e+04      9.10e-07\npolygon 276        98 1.57468e+05      9.43e-06\npolygon 277        14 4.58094e+03      2.74e-07\npolygon 278        22 5.23183e+03      3.13e-07\npolygon 279       231 7.48261e+04      4.48e-06\npolygon 280        17 3.13434e+03      1.88e-07\npolygon 281        18 6.41884e+03      3.85e-07\npolygon 282      3490 4.80502e+07      2.88e-03\npolygon 283      2677 1.19161e+08      7.14e-03\npolygon 284       472 3.37686e+06      2.02e-04\npolygon 285        16 4.51755e+03      2.71e-07\npolygon 286        86 7.10284e+04      4.25e-06\npolygon 287        31 1.06751e+04      6.39e-07\npolygon 288       272 1.62573e+06      9.74e-05\npolygon 289        46 5.15929e+04      3.09e-06\npolygon 290        13 1.18371e+04      7.09e-07\npolygon 291       107 1.07570e+05      6.44e-06\npolygon 292        73 5.79175e+04      3.47e-06\npolygon 293       290 3.84739e+06      2.30e-04\npolygon 294        11 9.78833e+02      5.86e-08\npolygon 295        17 2.15656e+03      1.29e-07\npolygon 296       501 3.43058e+06      2.06e-04\npolygon 297        33 2.80296e+04      1.68e-06\npolygon 298        39 1.40795e+04      8.43e-07\npolygon 299       160 2.12311e+05      1.27e-05\npolygon 300        47 4.13611e+03      2.48e-07\npolygon 301        31 1.91654e+04      1.15e-06\npolygon 302       794 7.28888e+06      4.37e-04\npolygon 303        28 5.95476e+03      3.57e-07\npolygon 304       148 1.47839e+05      8.86e-06\npolygon 305        28 1.39147e+04      8.34e-07\npolygon 306        52 9.07175e+03      5.43e-07\npolygon 307       102 3.22900e+04      1.93e-06\npolygon 308        21 6.55158e+03      3.92e-07\npolygon 309        13 7.96291e+03      4.77e-07\npolygon 310       235 2.19662e+06      1.32e-04\npolygon 311        49 3.32353e+04      1.99e-06\npolygon 312      3013 2.11761e+08      1.27e-02\npolygon 313        25 6.12931e+03      3.67e-07\npolygon 314        13 1.29657e+03      7.77e-08\npolygon 315        47 2.23896e+05      1.34e-05\npolygon 316        26 6.56360e+03      3.93e-07\npolygon 317        37 1.70858e+04      1.02e-06\npolygon 318        44 6.63087e+03      3.97e-07\npolygon 319        33 1.34250e+04      8.04e-07\npolygon 320       240 1.51037e+06      9.05e-05\npolygon 321        20 3.64277e+03      2.18e-07\npolygon 322        36 1.11851e+04      6.70e-07\npolygon 323        25 1.52203e+04      9.12e-07\npolygon 324      1458 2.22187e+07      1.33e-03\npolygon 325        25 1.06985e+04      6.41e-07\npolygon 326        42 4.37545e+04      2.62e-06\npolygon 327       435 2.35126e+06      1.41e-04\npolygon 328        40 4.75423e+04      2.85e-06\npolygon 329        19 5.08404e+03      3.05e-07\npolygon 330        53 5.46624e+04      3.27e-06\npolygon 331        36 3.00997e+04      1.80e-06\npolygon 332        24 1.57036e+04      9.41e-07\npolygon 333        23 1.35063e+04      8.09e-07\npolygon 334       293 1.14361e+06      6.85e-05\npolygon 335       203 4.34268e+05      2.60e-05\npolygon 336       141 3.73920e+05      2.24e-05\npolygon 337       357 1.20495e+06      7.22e-05\npolygon 338       174 4.77564e+05      2.86e-05\npolygon 339        79 6.88812e+04      4.13e-06\npolygon 340       702 5.20138e+06      3.12e-04\npolygon 341        17 9.99224e+02      5.99e-08\npolygon 342        70 5.87205e+04      3.52e-06\npolygon 343       457 1.78149e+06      1.07e-04\npolygon 344        42 4.19918e+04      2.52e-06\npolygon 345        21 5.33572e+03      3.20e-07\npolygon 346       485 3.15582e+06      1.89e-04\npolygon 347        75 2.04007e+05      1.22e-05\npolygon 348        84 3.48205e+04      2.09e-06\npolygon 349        72 1.72000e+05      1.03e-05\npolygon 350        41 3.05345e+04      1.83e-06\npolygon 351        19 1.19066e+03      7.13e-08\npolygon 352        23 1.14404e+04      6.85e-07\npolygon 353        42 4.25092e+04      2.55e-06\npolygon 354       522 1.29468e+06      7.76e-05\npolygon 355        72 1.56162e+05      9.35e-06\npolygon 356        39 2.31954e+04      1.39e-06\npolygon 357       337 1.69623e+06      1.02e-04\npolygon 358        26 8.69952e+02      5.21e-08\npolygon 359        60 5.55180e+03      3.33e-07\npolygon 360        71 1.18527e+05      7.10e-06\npolygon 361        52 4.79365e+04      2.87e-06\npolygon 362        23 1.46380e+03      8.77e-08\npolygon 363       152 7.26594e+05      4.35e-05\npolygon 364       336 1.04565e+06      6.26e-05\npolygon 365       369 3.83501e+06      2.30e-04\npolygon 366        23 1.35323e+03      8.11e-08\npolygon 367        14 9.44061e+02      5.66e-08\npolygon 368        20 1.19878e+03      7.18e-08\npolygon 369        20 1.22479e+03      7.34e-08\npolygon 370        12 3.14266e+02      1.88e-08\npolygon 371        96 5.74385e+05      3.44e-05\npolygon 372        16 1.47565e+03      8.84e-08\npolygon 373        11 3.37925e+02      2.02e-08\npolygon 374        28 1.20121e+04      7.20e-07\npolygon 375        18 5.11103e+03      3.06e-07\npolygon 376        30 4.15479e+03      2.49e-07\npolygon 377        19 1.44435e+03      8.65e-08\npolygon 378       257 8.82441e+05      5.29e-05\npolygon 379        17 1.40023e+03      8.39e-08\npolygon 380       190 4.78248e+05      2.86e-05\npolygon 381        25 7.73598e+03      4.63e-07\npolygon 382        72 1.55476e+04      9.31e-07\npolygon 383       707 7.43557e+06      4.45e-04\npolygon 384        91 2.54866e+05      1.53e-05\npolygon 385        64 1.03791e+05      6.22e-06\npolygon 386        14 3.56320e+03      2.13e-07\npolygon 387        71 4.83339e+04      2.90e-06\npolygon 388        17 4.75969e+03      2.85e-07\npolygon 389        18 3.58794e+03      2.15e-07\npolygon 390        31 1.65116e+04      9.89e-07\npolygon 391       102 6.27945e+04      3.76e-06\npolygon 392       127 3.73709e+05      2.24e-05\npolygon 393        22 8.17944e+02      4.90e-08\npolygon 394        20 1.23038e+03      7.37e-08\npolygon 395        83 1.55106e+03      9.29e-08\npolygon 396        20 2.32477e+03      1.39e-07\npolygon 397        35 1.36281e+04      8.16e-07\npolygon 398        38 1.64553e+04      9.86e-07\npolygon 399        39 1.01099e+04      6.06e-07\npolygon 400        50 9.42394e+02      5.65e-08\npolygon 401        63 3.44429e+03      2.06e-07\npolygon 402        16 9.61725e+02      5.76e-08\npolygon 403        20 5.47059e+03      3.28e-07\npolygon 404        24 1.12657e+04      6.75e-07\npolygon 405        25 3.23022e+03      1.94e-07\npolygon 406        26 8.94640e+03      5.36e-07\npolygon 407        20 5.05672e+03      3.03e-07\npolygon 408        14 5.21025e+02      3.12e-08\npolygon 409        68 3.42268e+03      2.05e-07\npolygon 410        23 4.53694e+03      2.72e-07\npolygon 411        45 1.87962e+03      1.13e-07\npolygon 412        18 1.50333e+03      9.01e-08\npolygon 413        18 3.10345e+03      1.86e-07\npolygon 414        10 5.35745e+02      3.21e-08\npolygon 415        21 3.63596e+03      2.18e-07\npolygon 416        13 1.02116e+03      6.12e-08\npolygon 417        12 1.73619e+03      1.04e-07\npolygon 418        23 7.61461e+03      4.56e-07\npolygon 419        19 4.49103e+03      2.69e-07\npolygon 420       711 3.82473e+06      2.29e-04\npolygon 421        15 1.38213e+03      8.28e-08\npolygon 422        17 5.43121e+03      3.25e-07\npolygon 423        21 1.97955e+03      1.19e-07\npolygon 424        22 1.66783e+03      9.99e-08\npolygon 425        15 7.33146e+02      4.39e-08\npolygon 426        39 4.29024e+04      2.57e-06\npolygon 427        24 2.68164e+03      1.61e-07\npolygon 428        25 2.98281e+03      1.79e-07\npolygon 429        30 4.40393e+03      2.64e-07\npolygon 430        14 7.05851e+02      4.23e-08\npolygon 431        11 6.69535e+02      4.01e-08\npolygon 432        14 6.42130e+02      3.85e-08\npolygon 433        15 6.02994e+02      3.61e-08\npolygon 434        11 5.50154e+02      3.30e-08\npolygon 435       117 4.46868e+05      2.68e-05\npolygon 436        28 1.31455e+04      7.87e-07\npolygon 437        24 6.53420e+03      3.91e-07\npolygon 438        95 3.16866e+04      1.90e-06\npolygon 439        68 7.41846e+03      4.44e-07\npolygon 440        20 1.57643e+03      9.44e-08\npolygon 441       297 4.65582e+05      2.79e-05\npolygon 442       108 8.38877e+04      5.03e-06\npolygon 443        90 2.65369e+05      1.59e-05\npolygon 444         6 2.47451e+02      1.48e-08\npolygon 445        63 8.35521e+03      5.01e-07\npolygon 446       114 5.16535e+04      3.09e-06\npolygon 447       389 1.08583e+06      6.50e-05\npolygon 448       391 7.99345e+05      4.79e-05\npolygon 449       136 1.63759e+05      9.81e-06\npolygon 450        50 6.32478e+04      3.79e-06\npolygon 451       219 2.54243e+05      1.52e-05\npolygon 452        53 6.25631e+04      3.75e-06\npolygon 453       278 2.66230e+05      1.59e-05\npolygon 454        38 2.90336e+03      1.74e-07\npolygon 455        26 2.48467e+03      1.49e-07\npolygon 456        41 6.89351e+03      4.13e-07\npolygon 457       299 4.00812e+05      2.40e-05\npolygon 458      1030 1.66243e+07      9.96e-04\npolygon 459        34 2.32389e+03      1.39e-07\npolygon 460        32 1.87841e+03      1.13e-07\npolygon 461        37 9.87386e+02      5.91e-08\npolygon 462       682 1.39226e+06      8.34e-05\npolygon 463        34 2.62560e+03      1.57e-07\npolygon 464        12 1.10550e+02      6.62e-09\npolygon 465        18 1.38831e+02      8.32e-09\npolygon 466        10 5.53120e+01      3.31e-09\npolygon 467        26 2.25004e+02      1.35e-08\npolygon 468        28 2.92620e+03      1.75e-07\npolygon 469       283 2.23929e+06      1.34e-04\npolygon 470        16 8.29282e+02      4.97e-08\npolygon 471        26 1.57985e+03      9.46e-08\npolygon 472       623 1.20943e+06      7.24e-05\npolygon 473        14 1.98308e+02      1.19e-08\npolygon 474        18 7.87079e+02      4.71e-08\npolygon 475        66 2.55809e+04      1.53e-06\npolygon 476        69 2.17800e+04      1.30e-06\npolygon 477        91 2.73187e+04      1.64e-06\npolygon 478        43 2.82278e+04      1.69e-06\npolygon 479        19 1.18992e+04      7.13e-07\npolygon 480        22 1.17190e+04      7.02e-07\npolygon 481        34 1.47055e+04      8.81e-07\npolygon 482        62 2.24563e+04      1.35e-06\npolygon 483        78 8.48842e+04      5.08e-06\npolygon 484        46 1.35989e+04      8.15e-07\npolygon 485         7 2.14611e+02      1.29e-08\npolygon 486        28 1.98540e+03      1.19e-07\npolygon 487        22 1.08368e+04      6.49e-07\npolygon 488        19 9.47042e+03      5.67e-07\npolygon 489         5 3.42089e+02      2.05e-08\npolygon 490        31 1.44650e+03      8.67e-08\npolygon 491         8 3.61796e+02      2.17e-08\npolygon 492         7 1.78403e+02      1.07e-08\npolygon 493        12 4.86579e+02      2.91e-08\npolygon 494         9 6.30641e+02      3.78e-08\npolygon 495       343 5.45240e+05      3.27e-05\npolygon 496       111 6.42841e+04      3.85e-06\npolygon 497        26 2.61765e+04      1.57e-06\npolygon 498         5 6.79484e+02      4.07e-08\npolygon 499         7 6.50446e+02      3.90e-08\npolygon 500       423 3.18233e+06      1.91e-04\npolygon 501        79 2.49961e+04      1.50e-06\npolygon 502        54 1.22067e+05      7.31e-06\npolygon 503        80 3.18143e+04      1.91e-06\npolygon 504        22 4.25083e+02      2.55e-08\npolygon 505        30 3.18447e+03      1.91e-07\npolygon 506        90 1.82111e+05      1.09e-05\npolygon 507        31 2.44090e+03      1.46e-07\npolygon 508        28 2.89515e+04      1.73e-06\npolygon 509        24 2.01142e+03      1.20e-07\npolygon 510        36 8.22704e+03      4.93e-07\npolygon 511        17 2.57702e+03      1.54e-07\npolygon 512         8 5.23581e+01      3.14e-09\npolygon 513        12 4.38046e+02      2.62e-08\npolygon 514        51 1.03129e+04      6.18e-07\npolygon 515       136 2.52678e+04      1.51e-06\npolygon 516        42 1.93188e+04      1.16e-06\npolygon 517        52 3.22341e+04      1.93e-06\npolygon 518        38 6.80476e+03      4.08e-07\npolygon 519        21 1.11895e+03      6.70e-08\npolygon 520        35 1.81671e+03      1.09e-07\npolygon 521       400 1.88255e+06      1.13e-04\npolygon 522        56 2.91054e+04      1.74e-06\npolygon 523       353 9.08138e+05      5.44e-05\npolygon 524        24 4.07068e+03      2.44e-07\npolygon 525       160 1.73580e+05      1.04e-05\npolygon 526       171 2.86639e+05      1.72e-05\npolygon 527       116 2.13804e+05      1.28e-05\npolygon 528        85 6.98799e+04      4.19e-06\npolygon 529       393 1.08414e+06      6.49e-05\npolygon 530        41 9.36420e+03      5.61e-07\npolygon 531        56 9.26379e+04      5.55e-06\npolygon 532       125 1.99837e+05      1.20e-05\npolygon 533        45 1.22254e+04      7.32e-07\npolygon 534        40 1.08040e+05      6.47e-06\npolygon 535         8 6.19200e+03      3.71e-07\npolygon 536         9 2.71560e+04      1.63e-06\nenclosing rectangle: [512066.8, 930756.9] x [9579205, 9834915] units\n                     (418700 x 255700 units)\nWindow area = 16693500000 square units\nFraction of frame area: 0.156\n```\n\n\n:::\n:::\n\n\n### 8.4 Computing Spatio-temporal KDE\n\n`spattemp.density()` from **sparr** is used to compute the STKDE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_yday <- spattemp.density(fire_yday_owin)\nsummary(kde_yday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 19110 (spatial)\n  lambda = 6.4541 (temporal)\n\nNo. of observations\n  905 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 930756.9] x [9579205, 9834915]\n\nTemporal bound\n  [10, 360]\n\nEvaluation\n  128 x 128 x 351 trivariate lattice\n  Density range: [2.75665e-27, 1.874119e-12]\n```\n\n\n:::\n:::\n\n\n::: callout-note\nThe spatial bandwidth (h = 19110) is identical to the monthly STKDE, since both use the same `kbb_owin` window. The temporal bandwidth (lambda = 6.4541) is much larger than the monthly version's lambda (0.0264), but this reflects the different scales used to measure time rather than a real difference in smoothing: `DayOfYear` spans a much wider numeric range (10 to 360) than `Month_num` (1 to 12), so a larger bandwidth value is expected.\n:::\n\n### 8.5 Plotting the Spatio-temporal KDE Object\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(kde_yday)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-12.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-13.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-14.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-15.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-16.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-17.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-18.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-19.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-20.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-21.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-22.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-23.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-24.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-25.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-26.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-27.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-28.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-29.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-30.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-31.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-32.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-33.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-34.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-35.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-36.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-37.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-38.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-39.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-40.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-41.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-42.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-43.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-44.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-45.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-46.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-47.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-48.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-49.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-50.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-51.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-52.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-53.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-54.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-55.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-56.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-57.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-58.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-59.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-60.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-61.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-62.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-63.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-64.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-65.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-66.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-67.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-68.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-69.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-70.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-71.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-72.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-73.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-74.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-75.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-76.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-77.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-78.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-79.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-80.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-81.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-82.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-83.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-84.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-85.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-86.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-87.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-88.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-89.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-90.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-91.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-92.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-93.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-94.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-95.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-96.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-97.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-98.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-99.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-100.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-101.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-102.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-103.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-104.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-105.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-106.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-107.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-108.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-109.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-110.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-111.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-112.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-113.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-114.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-115.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-116.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-117.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-118.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-119.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-120.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-121.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-122.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-123.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-124.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-125.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-126.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-127.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-128.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-129.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-130.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-131.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-132.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-133.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-134.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-135.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-136.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-137.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-138.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-139.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-140.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-141.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-142.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-143.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-144.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-145.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-146.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-147.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-148.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-149.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-150.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-151.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-152.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-153.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-154.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-155.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-156.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-157.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-158.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-159.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-160.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-161.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-162.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-163.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-164.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-165.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-166.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-167.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-168.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-169.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-170.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-171.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-172.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-173.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-174.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-175.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-176.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-177.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-178.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-179.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-180.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-181.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-182.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-183.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-184.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-185.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-186.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-187.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-188.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-189.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-190.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-191.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-192.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-193.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-194.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-195.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-196.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-197.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-198.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-199.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-200.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-201.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-202.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-203.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-204.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-205.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-206.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-207.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-208.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-209.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-210.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-211.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-212.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-213.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-214.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-215.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-216.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-217.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-218.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-219.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-220.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-221.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-222.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-223.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-224.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-225.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-226.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-227.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-228.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-229.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-230.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-231.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-232.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-233.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-234.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-235.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-236.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-237.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-238.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-239.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-240.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-241.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-242.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-243.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-244.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-245.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-246.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-247.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-248.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-249.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-250.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-251.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-252.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-253.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-254.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-255.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-256.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-257.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-258.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-259.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-260.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-261.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-262.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-263.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-264.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-265.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-266.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-267.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-268.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-269.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-270.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-271.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-272.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-273.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-274.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-275.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-276.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-277.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-278.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-279.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-280.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-281.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-282.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-283.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-284.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-285.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-286.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-287.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-288.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-289.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-290.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-291.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-292.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-293.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-294.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-295.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-296.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-297.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-298.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-299.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-300.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-301.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-302.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-303.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-304.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-305.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-306.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-307.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-308.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-309.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-310.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-311.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-312.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-313.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-314.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-315.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-316.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-317.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-318.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-319.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-320.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-321.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-322.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-323.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-324.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-325.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-326.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-327.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-328.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-329.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-330.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-331.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-332.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-333.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-334.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-335.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-336.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-337.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-338.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-339.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-340.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-341.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-342.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-343.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-344.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-345.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-346.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-347.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-348.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-349.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-350.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-26-351.png){width=672}\n:::\n:::\n\n\n## 9 Computing STKDE by Day of Year (Improved Method)\n\n`BOOT.spattemp()` from **sparr** performs bootstrap-based bandwidth selection for spatio-temporal density estimation, optimizing both the spatial and temporal bandwidths by minimizing an estimate of the Mean Integrated Squared Error (MISE), rather than relying on the automatic bandwidth selection used in the previous sections. The spatial bandwidth returned is isotropic, meaning the same amount of smoothing is applied in every direction, rather than allowing smoothing to vary by direction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)  #ensure reproducible results\nBOOT.spattemp(fire_yday_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInitialising...Done.\nOptimising...\nh = 19110 \b; lambda = 14.87514 \nh = 21021 \b; lambda = 14.87514 \nh = 19110 \b; lambda = 1925.875 \nh = 19587.75 \b; lambda = 970.375 \nh = 19826.62 \b; lambda = 492.625 \nh = 19946.06 \b; lambda = 253.7501 \nh = 20005.78 \b; lambda = 134.3126 \nh = 20035.64 \b; lambda = 74.59388 \nh = 20050.57 \b; lambda = 44.73451 \nh = 20058.03 \b; lambda = 29.80482 \nh = 20061.76 \b; lambda = 22.33998 \nh = 21972.76 \b; lambda = 22.33998 \nh = 23404.15 \b; lambda = 26.0724 \nh = 22444.91 \b; lambda = 33.53725 \nh = 21376.98 \b; lambda = 19.54067 \nh = 24719.36 \b; lambda = 23.27309 \nh = 27048.16 \b; lambda = 23.73964 \nh = 29075.33 \b; lambda = 30.27138 \nh = 27150.74 \b; lambda = 27.5887 \nh = 32719.34 \b; lambda = 27.93861 \nh = 37376.93 \b; lambda = 28.87172 \nh = 35349.76 \b; lambda = 22.33998 \nh = 38486.98 \b; lambda = 18.37428 \nh = 48815.75 \b; lambda = 23.50636 \nh = 43373.85 \b; lambda = 23.56468 \nh = 44483.9 \b; lambda = 13.06725 \nh = 42707.16 \b; lambda = 17.01837 \nh = 47594.03 \b; lambda = 22.20876 \nh = 45317.27 \b; lambda = 21.25014 \nh = 44650.57 \b; lambda = 14.70383 \nh = 43693.03 \b; lambda = 21.34947 \nh = 46303.15 \b; lambda = 25.58125 \nh = 43606.15 \b; lambda = 19.15909 \nh = 45230.39 \b; lambda = 19.05976 \nh = 45999.07 \b; lambda = 17.91491 \nh = 43519.28 \b; lambda = 16.9687 \nh = 44867.77 \b; lambda = 20.17978 \nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          h      lambda \n45230.39047    19.05976 \n```\n\n\n:::\n:::\n\n\n### 9.1 Computing Spatio-temporal KDE\n\nThe STKDE is derived using the h and lambda values obtained from `BOOT.spattemp()` in the previous step.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_yday <- spattemp.density(fire_yday_owin,\n                              h = 45000,\n                              lambda = 19)\nsummary(kde_yday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 45000 (spatial)\n  lambda = 19 (temporal)\n\nNo. of observations\n  905 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 930756.9] x [9579205, 9834915]\n\nTemporal bound\n  [10, 360]\n\nEvaluation\n  128 x 128 x 351 trivariate lattice\n  Density range: [5.259942e-16, 9.940862e-13]\n```\n\n\n:::\n:::\n\n\n### 9.2 Plotting the Spatio-temporal KDE Object\n\nThe resulting spatio-temporal KDE surfaces are shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(kde_yday)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-12.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-13.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-14.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-15.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-16.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-17.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-18.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-19.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-20.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-21.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-22.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-23.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-24.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-25.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-26.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-27.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-28.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-29.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-30.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-31.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-32.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-33.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-34.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-35.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-36.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-37.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-38.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-39.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-40.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-41.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-42.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-43.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-44.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-45.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-46.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-47.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-48.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-49.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-50.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-51.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-52.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-53.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-54.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-55.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-56.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-57.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-58.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-59.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-60.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-61.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-62.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-63.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-64.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-65.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-66.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-67.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-68.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-69.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-70.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-71.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-72.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-73.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-74.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-75.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-76.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-77.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-78.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-79.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-80.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-81.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-82.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-83.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-84.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-85.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-86.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-87.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-88.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-89.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-90.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-91.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-92.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-93.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-94.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-95.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-96.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-97.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-98.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-99.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-100.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-101.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-102.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-103.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-104.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-105.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-106.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-107.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-108.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-109.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-110.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-111.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-112.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-113.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-114.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-115.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-116.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-117.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-118.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-119.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-120.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-121.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-122.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-123.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-124.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-125.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-126.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-127.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-128.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-129.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-130.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-131.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-132.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-133.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-134.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-135.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-136.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-137.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-138.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-139.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-140.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-141.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-142.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-143.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-144.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-145.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-146.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-147.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-148.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-149.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-150.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-151.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-152.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-153.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-154.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-155.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-156.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-157.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-158.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-159.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-160.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-161.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-162.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-163.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-164.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-165.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-166.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-167.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-168.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-169.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-170.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-171.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-172.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-173.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-174.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-175.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-176.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-177.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-178.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-179.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-180.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-181.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-182.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-183.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-184.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-185.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-186.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-187.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-188.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-189.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-190.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-191.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-192.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-193.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-194.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-195.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-196.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-197.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-198.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-199.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-200.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-201.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-202.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-203.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-204.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-205.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-206.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-207.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-208.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-209.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-210.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-211.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-212.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-213.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-214.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-215.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-216.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-217.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-218.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-219.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-220.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-221.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-222.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-223.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-224.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-225.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-226.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-227.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-228.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-229.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-230.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-231.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-232.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-233.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-234.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-235.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-236.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-237.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-238.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-239.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-240.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-241.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-242.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-243.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-244.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-245.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-246.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-247.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-248.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-249.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-250.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-251.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-252.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-253.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-254.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-255.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-256.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-257.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-258.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-259.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-260.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-261.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-262.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-263.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-264.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-265.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-266.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-267.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-268.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-269.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-270.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-271.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-272.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-273.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-274.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-275.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-276.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-277.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-278.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-279.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-280.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-281.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-282.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-283.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-284.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-285.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-286.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-287.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-288.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-289.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-290.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-291.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-292.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-293.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-294.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-295.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-296.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-297.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-298.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-299.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-300.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-301.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-302.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-303.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-304.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-305.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-306.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-307.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-308.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-309.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-310.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-311.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-312.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-313.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-314.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-315.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-316.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-317.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-318.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-319.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-320.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-321.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-322.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-323.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-324.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-325.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-326.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-327.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-328.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-329.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-330.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-331.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-332.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-333.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-334.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-335.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-336.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-337.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-338.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-339.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-340.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-341.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-342.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-343.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-344.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-345.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-346.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-347.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-348.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-349.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-350.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-29-351.png){width=672}\n:::\n:::\n\n\n## 10 Spatio-temporal Point Patterns Analysis: stpp methods\n\nThis section covers spatio-temporal point pattern analysis using functions from the [**stpp**](https://www.jstatsoft.org/article/view/v053i02) package.\n\n### 10.1 Preparing the Spatio-temporal Point Process Object for stpp\n\n**Step 1:** Extracting forest fire coordinates from the fire point events\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- st_coordinates(fire_sf)\n```\n:::\n\n\n**Step 2:** Creating a data frame by combining the x- and y-coordinates and temporal event. *Note that the temporal event must be in integer.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_df <- data.frame(\n  x = coords[, 1],\n  y = coords[, 2],\n  t = fire_sf$DayOfYear\n)\n```\n:::\n\n\n**Step 3:** Creating stpp spatio-temporal object `as.3dpoints()` is used to convert the data frame into an stpp spatio-temporal object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_stpp <- as.3dpoints(fire_df)\nclass(fire_stpp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"stpp\"\n```\n\n\n:::\n:::\n\n\nThe result can be visualised below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fire_stpp)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\nThe xy-locations plot shows fire events split into two separate clusters, one over Bangka Island and a smaller one over Belitung and its nearby islands, with a clear gap between them where the sea separates the two.\n\nThe cumulative number panel shows the total fire count increasing slowly from January to May, then climbing sharply from around July to November, before levelling off toward the end of the year. This steep rise corresponds to the fire season identified in the earlier monthly maps and KDE surfaces.\n:::\n\n### 10.2 Computing spatio-temporal K-function\n\n[STIKhat()](https://cran.r-project.org/web/packages/stpp/refman/stpp.html#STIKhat) from **stpp** is used to compute the space-time inhomogeneous K-function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_stik <- STIKhat(fire_stpp)\n```\n:::\n\n\nThe result can be visualised using `plotK()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotK(kbb_stik)\n```\n:::\n\n\n![](kbb_stik.png)\n\n::: {.callout-note}\n**Analysis:** \n\nNo contour lines appear near the bottom-left of the plot (short spatial distance, short time lag), since the K-function values there fall below the lowest threshold shown. Contour lines begin to appear only at moderate distances and time lags, then fan out in a rippling pattern towards the top-right, with lines becoming more closely spaced as both u and v increase. This pattern is consistent with forest fire events in Kepulauan Bangka Belitung not being independent in space and time. A formal comparison against the theoretical K-function under spatial randomness would be needed to confirm this statistically.\n:::\n\n## 11 Reference\n\nPeter Hall (1990) \"[Using the Bootstrap to Estimate Mean Squared Error and Select Smoothing Parameter in Nonparametric Problems](http://www.sciencedirect.com/science/article/pii/0047-259X(90)90080-2)\", *Journal of Multivariate Analysis*, Vol. 32, pp. 177-203.\n",
    "supporting": [
      "Hands-on_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}