---
title: "Hands-on Exercise 2A: First-order Spatial Point Pattern Analysis (1st-SPPA)"
---

## 1 Overview

**Spatial Point Pattern Analysis (SPPA)** is the evaluation of the pattern or distribution of a set of points on a surface. The points may represent:

- events such as crimes, traffic accidents, or disease onsets, or
- business services (e.g., coffee shops and fast-food outlets) or facilities such as childcare centres and eldercare centres.

**First-order Spatial Point Pattern Analysis (1st-SPPA)** focuses on understanding the intensity or density of points across a study area. It examines how the distribution of points varies over space, essentially identifying trends or patterns in point density. This type of analysis deals with the individual locations of points and their distribution, without considering interactions between them.

This exercise uses [**spatstat**](https://cran.r-project.org/web/packages/spatstat/) to perform two commonly used 1st-order SPPA methods, applied to childcare centres in Singapore. 

The specific questions to be answered are:

- Are the childcare centres in Singapore randomly distributed throughout the country?
- If the answer is not, then the next logical question is: where are the locations with higher concentration of childcare centres?

