<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-19">

<title>Take-home Exercise 1: Geospatial Analytics for Public Safety – ISSS626 Geospatial Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-172ba59bd5e0b52282274ba0c0cc16fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626 Geospatial Analytics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01A/Hands-on_Ex01A.html">
 <span class="dropdown-text">Hands-on Exercise 1A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01B/Hands-on_Ex01B.html">
 <span class="dropdown-text">Hands-on Exercise 1B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02A/Hands-on_Ex02A.html">
 <span class="dropdown-text">Hands-on Exercise 2A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02B/Hands-on_Ex02B.html">
 <span class="dropdown-text">Hands-on Exercise 2B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Yxlinn/ISSS626-GAA"> <i class="bi bi-github" role="img" aria-label="GitHub Repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">1 Overview</a></li>
  <li><a href="#analytical-questions" id="toc-analytical-questions" class="nav-link" data-scroll-target="#analytical-questions">2 Analytical Questions</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">3 The Data</a></li>
  <li><a href="#installing-and-loading-the-r-packages" id="toc-installing-and-loading-the-r-packages" class="nav-link" data-scroll-target="#installing-and-loading-the-r-packages">4 Installing and Loading the R Packages</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">5 Reproducibility</a></li>
  <li><a href="#importing-and-preparing-the-data" id="toc-importing-and-preparing-the-data" class="nav-link" data-scroll-target="#importing-and-preparing-the-data">6 Importing and Preparing the Data</a>
  <ul>
  <li><a href="#thailand-road-accident-data" id="toc-thailand-road-accident-data" class="nav-link" data-scroll-target="#thailand-road-accident-data">6.1 Thailand Road Accident Data</a></li>
  <li><a href="#administrative-boundaries-bangkok-metropolitan-region-bmr" id="toc-administrative-boundaries-bangkok-metropolitan-region-bmr" class="nav-link" data-scroll-target="#administrative-boundaries-bangkok-metropolitan-region-bmr">6.2 Administrative Boundaries: Bangkok Metropolitan Region (BMR)</a></li>
  <li><a href="#road-network" id="toc-road-network" class="nav-link" data-scroll-target="#road-network">6.3 Road Network</a></li>
  </ul></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering">7 Feature Engineering</a></li>
  <li><a href="#spatial-point-pattern-analysis-sppa" id="toc-spatial-point-pattern-analysis-sppa" class="nav-link" data-scroll-target="#spatial-point-pattern-analysis-sppa">8 Spatial Point Pattern Analysis (SPPA)</a>
  <ul>
  <li><a href="#constructing-the-point-pattern-objects" id="toc-constructing-the-point-pattern-objects" class="nav-link" data-scroll-target="#constructing-the-point-pattern-objects">8.1 Constructing the Point Pattern Objects</a></li>
  </ul></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">Reference</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 1: Geospatial Analytics for Public Safety</h1>
<p class="subtitle lead">Spatial and Spatio-Temporal Point Pattern Analysis of Road Traffic Accidents in the Bangkok Metropolitan Region</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 19, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 22, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">1 Overview</h2>
<p>Public safety planning increasingly relies on location-based evidence to identify where and when incidents concentrate, so that enforcement, engineering, and policy responses can be targeted rather than applied uniformly across a region. Road traffic accidents are a point event well suited to this type of analysis: each incident carries a location and a time, and the accumulated pattern of incidents can reveal whether risk is randomly scattered or systematically concentrated in identifiable places and periods.</p>
<p>This exercise applies spatial and spatio-temporal point pattern analysis to road traffic accident data for the <a href="https://en.wikipedia.org/wiki/Bangkok_Metropolitan_Region">Bangkok Metropolitan Region (BMR)</a>, Thailand, covering Bangkok and the five adjacent provinces of Nonthaburi, Nakhon Pathom, Pathum Thani, Samut Prakan, and Samut Sakhon.</p>
</section>
<section id="analytical-questions" class="level2">
<h2 class="anchored" data-anchor-id="analytical-questions">2 Analytical Questions</h2>
<ol type="1">
<li>How is the intensity of road traffic accidents distributed across space and time within the BMR?</li>
<li>Do accidents exhibit statistically significant spatial and spatio-temporal clustering, beyond what would be expected under complete spatial randomness?</li>
<li>Does accounting for the road network materially change the interpretation of accident concentration, compared to treating accidents as freely distributed in planar space?</li>
<li>What do the resulting patterns imply for public safety planning and resource allocation within the region?</li>
</ol>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">3 The Data</h2>
<p>Three datasets are used in this exercise:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Dataset</th>
<th>Description</th>
<th>Format</th>
<th>Source</th>
<th>Date Accessed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Thailand Road Accident (2019 to 2022)</td>
<td>Accident-level records with location, timing, severity, and contributing-factor fields, sourced from the Ministry of Transport’s TRAMS dashboard. <strong>Only the 2022 subset is used for this study.</strong></td>
<td>CSV</td>
<td><a href="https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022">Kaggle</a></td>
<td>20 Sep 2026</td>
</tr>
<tr class="even">
<td>Thailand Administrative Boundaries, ADM2</td>
<td>District-level administrative boundaries for Thailand</td>
<td>GeoJSON</td>
<td><a href="https://www.geoboundaries.org">geoBoundaries</a></td>
<td>20 Sep 2026</td>
</tr>
<tr class="odd">
<td>Thailand Road Network (OpenStreetMap extract)</td>
<td>Line-based road network for Thailand, classified by highway type under the <code>fclass</code> field</td>
<td>Shapefile</td>
<td><a href="https://download.geofabrik.de/asia/thailand.html">Geofabrik</a></td>
<td>20 Sep 2026</td>
</tr>
</tbody>
</table>
</section>
<section id="installing-and-loading-the-r-packages" class="level2">
<h2 class="anchored" data-anchor-id="installing-and-loading-the-r-packages">4 Installing and Loading the R Packages</h2>
<p>The following R packages are used across this exercise:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Package</th>
<th>Purpose</th>
<th>Use Case in This Exercise</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>tidyverse</strong></td>
<td>Collection of packages for data import, manipulation, and visualisation</td>
<td>Importing, cleaning, and transforming the accident dataset</td>
</tr>
<tr class="even">
<td><strong>sf</strong></td>
<td>Imports, manages, and processes vector-based geospatial data</td>
<td>Handling the administrative boundary and road network data, and constructing spatial point objects from the accident coordinates</td>
</tr>
<tr class="odd">
<td><strong>spatstat</strong></td>
<td>Toolkit for spatial point pattern analysis</td>
<td>First-order (KDE, quadrat) and second-order (G, F, K, L functions) analysis of accident intensity and clustering</td>
</tr>
<tr class="even">
<td><strong>sparr</strong></td>
<td>Kernel estimation of spatial and spatio-temporal densities</td>
<td>Spatio-temporal KDE of accident intensity across months in 2022</td>
</tr>
<tr class="odd">
<td><strong>stpp</strong></td>
<td>Analysis of second-order properties of spatio-temporal point processes</td>
<td>Testing for space-time interaction beyond what spatial and temporal clustering alone would predict</td>
</tr>
<tr class="even">
<td><strong>spNetwork</strong></td>
<td>Spatial analysis constrained to a network</td>
<td>Network-constrained kernel density estimation (NKDE) of accidents along the road network</td>
</tr>
<tr class="odd">
<td><strong>tmap</strong></td>
<td>Static and interactive thematic mapping</td>
<td>Choropleth maps, KDE surfaces, and accident point maps throughout the report</td>
</tr>
<tr class="even">
<td><strong>knitr</strong></td>
<td>Dynamic report generation</td>
<td>Rendering tables and controlling code chunk output in this document</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, sf, spatstat, sparr, stpp, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               spNetwork, tmap, knitr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility">5 Reproducibility</h2>
<p>A fixed seed value of 123 is set for reproducibility of any simulation-based procedure used later in this exercise.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="importing-and-preparing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-and-preparing-the-data">6 Importing and Preparing the Data</h2>
<p>This section imports and prepares each of the three datasets described above. The study area for this exercise is the Bangkok Metropolitan Region (BMR), operationalised at the district (ADM2) level, and the study period is restricted to 2022.</p>
<section id="thailand-road-accident-data" class="level3">
<h3 class="anchored" data-anchor-id="thailand-road-accident-data">6.1 Thailand Road Accident Data</h3>
<p>The accident dataset is imported using <em>read_csv()</em> of the <strong>readr</strong> package:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>rdacc <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/thai_road_accident_2019_2022.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Null values are checked across every column:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(rdacc))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   acc_code           incident_datetime 
                          0                           0 
            report_datetime                 province_th 
                          0                           0 
                province_en                      agency 
                          0                           0 
                      route                vehicle_type 
                          0                           0 
             presumed_cause               accident_type 
                          0                           0 
number_of_vehicles_involved        number_of_fatalities 
                          0                           0 
         number_of_injuries           weather_condition 
                          0                           0 
                   latitude                   longitude 
                        359                         359 
           road_description           slope_description 
                          0                           0 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Analysis:</strong></p>
<p>Of the 359 rows with missing coordinates, 350 are attributed to a single agency, the Expressway Authority of Thailand. The other two agencies, Department of Highways and Department of Rural Roads, have almost none missing. The affected rows are concentrated in Bangkok and in the 2021 to 2022 period. These rows cannot be placed spatially, so they are dropped from the point pattern analysis. As a result, accidents attributed to the Expressway Authority, largely Bangkok’s controlled-access expressway network, are undercounted relative to the other two agencies.</p>
</div>
</div>
<p>Exact duplicate rows are checked next:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">duplicated</span>(rdacc))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>The set of provinces represented in the data is inspected, since only accidents within the six BMR provinces are relevant to this exercise:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">unique</span>(rdacc<span class="sc">$</span>province_en))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Amnat Charoen"            "Ang Thong"               
 [3] "Bangkok"                  "buogkan"                 
 [5] "Buri Ram"                 "Chachoengsao"            
 [7] "Chai Nat"                 "Chaiyaphum"              
 [9] "Chanthaburi"              "Chiang Mai"              
[11] "Chiang Rai"               "Chon Buri"               
[13] "Chumphon"                 "Kalasin"                 
[15] "Kamphaeng Phet"           "Kanchanaburi"            
[17] "Khon Kaen"                "Krabi"                   
[19] "Lampang"                  "Lamphun"                 
[21] "Loburi"                   "Loei"                    
[23] "Mae Hong Son"             "Maha Sarakham"           
[25] "Mukdahan"                 "Nakhon Nayok"            
[27] "Nakhon Pathom"            "Nakhon Phanom"           
[29] "Nakhon Ratchasima"        "Nakhon Sawan"            
[31] "Nakhon Si Thammarat"      "Nan"                     
[33] "Narathiwat"               "Nong Bua Lam Phu"        
[35] "Nong Khai"                "Nonthaburi"              
[37] "Pathum Thani"             "Pattani"                 
[39] "Phangnga"                 "Phatthalung"             
[41] "Phayao"                   "Phetchabun"              
[43] "Phetchaburi"              "Phichit"                 
[45] "Phitsanulok"              "Phra Nakhon Si Ayutthaya"
[47] "Phrae"                    "Phuket"                  
[49] "Prachin Buri"             "Prachuap Khiri Khan"     
[51] "Ranong"                   "Ratchaburi"              
[53] "Rayong"                   "Roi Et"                  
[55] "Sa Kaeo"                  "Sakon Nakhon"            
[57] "Samut Prakan"             "Samut Sakhon"            
[59] "Samut Songkhram"          "Saraburi"                
[61] "Satun"                    "Si Sa Ket"               
[63] "Sing Buri"                "Songkhla"                
[65] "Sukhothai"                "Suphan Buri"             
[67] "Surat Thani"              "Surin"                   
[69] "Tak"                      "Trang"                   
[71] "Trat"                     "Ubon Ratchathani"        
[73] "Udon Thani"               "unknown"                 
[75] "Uthai Thani"              "Uttaradit"               
[77] "Yala"                     "Yasothon"                </code></pre>
</div>
</div>
<p>The six BMR province names are confirmed to appear exactly as expected in the list above (Bangkok, Nonthaburi, Nakhon Pathom, Pathum Thani, Samut Prakan, Samut Sakhon).</p>
<p>The dataset is filtered to the study area (BMR) and study period (2022), and limited to rows with valid coordinates. It is then converted into a spatial point object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>bmr_provinces <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Bangkok"</span>, <span class="st">"Nonthaburi"</span>, <span class="st">"Nakhon Pathom"</span>, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Pathum Thani"</span>, <span class="st">"Samut Prakan"</span>, <span class="st">"Samut Sakhon"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>accidents_bmr <span class="ot">&lt;-</span> rdacc <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(province_en <span class="sc">%in%</span> bmr_provinces,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>         <span class="fu">year</span>(incident_datetime) <span class="sc">==</span> <span class="dv">2022</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(latitude), <span class="sc">!</span><span class="fu">is.na</span>(longitude)) <span class="sc">%&gt;%</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32647</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><a href="https://epsg.io/4326">crs = 4326</a> labels the coordinates as WGS84 decimal degrees</li>
<li><a href="crs = 32647">crs = 32647</a> then reprojects them into UTM Zone 47N (metres). EPSG:32647 specifically covers 96°E to 102°E, the zone the BMR provinces fall within; this reprojection is needed for the distance- and area-based methods used later.</li>
</ul>
</div>
</div>
</section>
<section id="administrative-boundaries-bangkok-metropolitan-region-bmr" class="level3">
<h3 class="anchored" data-anchor-id="administrative-boundaries-bangkok-metropolitan-region-bmr">6.2 Administrative Boundaries: Bangkok Metropolitan Region (BMR)</h3>
<p>Thailand’s administrative boundaries run from country (ADM0), through province (ADM1), district (ADM2), to sub-district (ADM3).</p>
<p>This exercise uses both ADM1 and ADM2: ADM1 identifies the six provinces that make up the BMR by name, and ADM2 supplies the actual study area boundary at finer district resolution, needed later for the network-constrained analysis. ADM2’s own attribute table does not record which province each district belongs to, so the two levels are combined through a spatial join.</p>
<p>ADM1 is imported first, since it supplies the province names needed to define the BMR.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>tha_adm1 <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/geoBoundaries-THA-ADM1.geojson"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `geoBoundaries-THA-ADM1' from data source 
  `C:\yxlinn\ISSS626-GAA\Take-home_Ex\Take-home_Ex01\data\geoBoundaries-THA-ADM1.geojson' 
  using driver `GeoJSON'
Simple feature collection with 77 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 97.34381 ymin: 5.612851 xmax: 105.6368 ymax: 20.46483
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tha_adm1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 99.08799 ymin: 13.17157 xmax: 104.3559 ymax: 19.73551
Geodetic CRS:  WGS 84
                  shapeName shapeISO                 shapeID shapeGroup
1           Roi Et Province    TH-45 36821470B96343765829948        THA
2           Phayao Province    TH-56 36821470B12194119812739        THA
3     Nakhon Sawan Province    TH-60 36821470B58837026258254        THA
4 Nong Bua Lam Phu Province    TH-39 36821470B48254980905782        THA
5     Chachoengsao Province    TH-24 36821470B91271468807469        THA
6            Surin Province    TH-32 36821470B33660676013176        THA
  shapeType                       geometry
1      ADM1 MULTIPOLYGON (((103.5111 16...
2      ADM1 MULTIPOLYGON (((99.68719 19...
3      ADM1 MULTIPOLYGON (((99.08899 15...
4      ADM1 MULTIPOLYGON (((102.0808 17...
5      ADM1 MULTIPOLYGON (((100.849 13....
6      ADM1 MULTIPOLYGON (((103.4048 15...</code></pre>
</div>
</div>
<p>The full list of province names is checked before filtering:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">unique</span>(tha_adm1<span class="sc">$</span>shapeName))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Amnat Charoen Province"            "Ang Thong Province"               
 [3] "Bangkok"                           "Bueng Kan Province"               
 [5] "Buri Ram Province"                 "Chachoengsao Province"            
 [7] "Chai Nat Province"                 "Chaiyaphum Province"              
 [9] "Chanthaburi Province"              "Chiang Mai Province"              
[11] "Chiang Rai Province"               "Chon Buri Province"               
[13] "Chumphon Province"                 "Kalasin"                          
[15] "Kamphaeng Phet Province"           "Kanchanaburi Province"            
[17] "Khon Kaen Province"                "Krabi Province"                   
[19] "Lampang Province"                  "Lamphun Province"                 
[21] "Loei Province"                     "Lopburi Province"                 
[23] "Mae Hong Son Province"             "Maha Sarakham Province"           
[25] "Mukdahan Province"                 "Nakhon Nayok Province"            
[27] "Nakhon Pathom Province"            "Nakhon Phanom Province"           
[29] "Nakhon Ratchasima Province"        "Nakhon Sawan Province"            
[31] "Nakhon Si Thammarat Province"      "Nan Province"                     
[33] "Narathiwat Province"               "Nong Bua Lam Phu Province"        
[35] "Nong Khai Province"                "Nonthaburi Province"              
[37] "Pathum Thani Province"             "Pattani Province"                 
[39] "Phangnga Province"                 "Phatthalung Province"             
[41] "Phayao Province"                   "Phetchabun Province"              
[43] "Phetchaburi Province"              "Phichit Province"                 
[45] "Phitsanulok Province"              "Phra Nakhon Si Ayutthaya Province"
[47] "Phrae Province"                    "Phuket Province"                  
[49] "Prachin Buri Province"             "Prachuap Khiri Khan Province"     
[51] "Ranong Province"                   "Ratchaburi Province"              
[53] "Rayong Province"                   "Roi Et Province"                  
[55] "Sa Kaeo Province"                  "Sakon Nakhon Province"            
[57] "Samut Prakan Province"             "Samut Sakhon Province"            
[59] "Samut Songkhram Province"          "Saraburi Province"                
[61] "Satun Province"                    "Si Sa Ket Province"               
[63] "Sing Buri Province"                "Songkhla Province"                
[65] "Sukhothai Province"                "Suphan Buri Province"             
[67] "Surat Thani Province"              "Surin Province"                   
[69] "Tak Province"                      "Trang Province"                   
[71] "Trat Province"                     "Ubon Ratchathani Province"        
[73] "Udon Thani Province"               "Uthai Thani Province"             
[75] "Uttaradit Province"                "Yala Province"                    
[77] "Yasothon Province"                </code></pre>
</div>
</div>
<p>Next, ADM2 is imported to supply the actual study area boundary.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>tha_adm2 <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/geoBoundaries-THA-ADM2.geojson"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `geoBoundaries-THA-ADM2' from data source 
  `C:\yxlinn\ISSS626-GAA\Take-home_Ex\Take-home_Ex01\data\geoBoundaries-THA-ADM2.geojson' 
  using driver `GeoJSON'
Simple feature collection with 928 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tha_adm2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 98.6116 ymin: 6.471538 xmax: 104.0843 ymax: 17.82245
Geodetic CRS:  WGS 84
      shapeName shapeISO                 shapeID shapeGroup shapeType
1   Akat Amnuai          78962969B83463915016953        THA      ADM2
2       Amphawa          78962969B68169586280131        THA      ADM2
3       Ao Luek          78962969B54777225393770        THA      ADM2
4 Aranyaprathet          78962969B18658138340114        THA      ADM2
5      At Samat          78962969B71289419444255        THA      ADM2
6         Bacho          78962969B22586560209583        THA      ADM2
                        geometry
1 MULTIPOLYGON (((104.0122 17...
2 MULTIPOLYGON (((100.0144 13...
3 MULTIPOLYGON (((98.69051 8....
4 MULTIPOLYGON (((102.5356 13...
5 MULTIPOLYGON (((103.8999 15...
6 MULTIPOLYGON (((101.7093 6....</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>tha_adm2</code> has 928 features and five attribute fields: shapeName, shapeISO, shapeID, shapeGroup, and shapeType. None of the fields represent a parent province. The BMR district set therefore cannot be filtered by attribute and is derived spatially against ADM1.</p>
</div>
</div>
<p>Both boundaries are reprojected to EPSG:32647.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>tha_adm1 <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(tha_adm1, <span class="at">crs =</span> <span class="dv">32647</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>tha_adm2 <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(tha_adm2, <span class="at">crs =</span> <span class="dv">32647</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The six BMR provinces are filtered out of ADM1:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>bmr_provinces_adm1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Bangkok"</span>, </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Nonthaburi Province"</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Nakhon Pathom Province"</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Pathum Thani Province"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Samut Prakan Province"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Samut Sakhon Province"</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>adm1_bmr <span class="ot">&lt;-</span> tha_adm1 <span class="sc">%&gt;%</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(shapeName <span class="sc">%in%</span> bmr_provinces_adm1) <span class="sc">%&gt;%</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">province_name =</span> shapeName)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(adm1_bmr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>shapeName</code> is renamed to <code>province_name</code> to avoid a duplicate column when joined to <code>tha_adm2</code>, which carries its own <code>shapeName</code> field for district names.</p>
</div>
</div>
<p>Each ADM2 district is then assigned to whichever ADM1 province it overlaps most with, and only those districts assigned to one of the six BMR provinces are kept.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>adm2_bmr <span class="ot">&lt;-</span> <span class="fu">st_join</span>(tha_adm2, adm1_bmr, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">join =</span> st_intersects, </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">largest =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(province_name)) <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(shapeName, province_name, geometry)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>adm2_bmr <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(province_name)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           province_name  n
1                Bangkok 52
2 Nakhon Pathom Province 11
3    Nonthaburi Province  7
4  Pathum Thani Province 14
5  Samut Prakan Province  8
6  Samut Sakhon Province  5</code></pre>
</div>
</div>
<p>The resulting <code>adm2_bmr</code> is the study area boundary used for the remainder of this exercise.</p>
<p>As a visual check, the boundary is plotted and coloured by province. This shows whether the districts form one connected region, or whether any district ended up misplaced or disconnected, something the count above could not reveal.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(adm2_bmr) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"province_name"</span>,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Province"</span>, <span class="at">na.show =</span> <span class="cn">FALSE</span>)) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"BMR Study Area by Province"</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="road-network" class="level3">
<h3 class="anchored" data-anchor-id="road-network">6.3 Road Network</h3>
<p>The road network is imported and inspected:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>roads <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/gis_osm_roads_free_1.shp"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `gis_osm_roads_free_1' from data source 
  `C:\yxlinn\ISSS626-GAA\Take-home_Ex\Take-home_Ex01\data\gis_osm_roads_free_1.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 2930769 features and 10 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 97.31354 ymin: 5.643645 xmax: 105.6481 ymax: 20.47168
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(roads)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,930,769
Columns: 11
$ osm_id   &lt;chr&gt; "4270622", "4828442", "4828443", "4828444", "4828446", "85607…
$ code     &lt;int&gt; 5122, 5122, 5122, 5122, 5122, 5122, 5122, 5122, 5122, 5153, 5…
$ fclass   &lt;chr&gt; "residential", "residential", "residential", "residential", "…
$ name     &lt;chr&gt; "ถนนศิริมังคลาจารย์ ซอย1", "Soi Ruam- U-Thit", "Soi Ruam- U-Thit"…
$ ref      &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ oneway   &lt;chr&gt; "B", "B", "B", "B", "B", "B", "F", "B", "F", "B", "F", "F", "…
$ maxspeed &lt;int&gt; 0, 0, 0, 0, 0, 30, 30, 0, 0, 0, 50, 0, 60, 0, 0, 60, 60, 60, …
$ layer    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 2…
$ bridge   &lt;chr&gt; "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "T", "…
$ tunnel   &lt;chr&gt; "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "…
$ geometry &lt;LINESTRING [°]&gt; LINESTRING (98.97274 18.796..., LINESTRING (98.341…</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(roads)<span class="sc">$</span>input</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "WGS 84"</code></pre>
</div>
</div>
<p>The highway classification is inspected via the <code>fclass</code> field:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">unique</span>(roads<span class="sc">$</span>fclass))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "bridleway"      "busway"         "cycleway"       "footway"       
 [5] "living_street"  "motorway"       "motorway_link"  "path"          
 [9] "pedestrian"     "primary"        "primary_link"   "residential"   
[13] "secondary"      "secondary_link" "service"        "steps"         
[17] "tertiary"       "tertiary_link"  "track"          "track_grade1"  
[21] "track_grade2"   "track_grade3"   "track_grade4"   "track_grade5"  
[25] "trunk"          "trunk_link"     "unclassified"   "unknown"       </code></pre>
</div>
</div>
<p>The road network is reprojected to EPSG:32647.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>roads <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(roads, <span class="at">crs =</span> <span class="dv">32647</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>For the purpose of this study, the network is filtered to the intercity highway classes based on the <a href="https://wiki.openstreetmap.org/wiki/Thailand/Conventions">WikiProject Thailand highway classification convention</a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>highway_types <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"motorway"</span>, <span class="st">"motorway_link"</span>, </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"trunk"</span>,<span class="st">"trunk_link"</span>, </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"primary"</span>, <span class="st">"primary_link"</span>,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"secondary"</span>, <span class="st">"secondary_link"</span>,</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"tertiary"</span>, <span class="st">"tertiary_link"</span>, </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"unclassified"</span>)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>roads_filtered <span class="ot">&lt;-</span> roads <span class="sc">%&gt;%</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(fclass <span class="sc">%in%</span> highway_types)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The 28 <code>fclass</code> values include a <code>_link</code> variant for five of the six target classes, representing ramps and interchange connectors rather than a separate road type. These are kept alongside their base class, since dropping them would leave a gap at every interchange, breaking the network needed for the network-constrained analysis later. The rest are excluded as non-vehicular, local, or unclassifiable.</p>
</div>
</div>
<p>The filtered network is then clipped to the BMR study area:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>roads_bmr <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(roads_filtered, adm2_bmr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Clipping lines against polygons with <code>st_intersection()</code> can change geometry types. For example, a line that only touches a polygon boundary at a single point can come out as a point instead of a line. Therefore, the geometry types present in <code>roads_bmr</code> are checked.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry_type</span>(roads_bmr) <span class="sc">|&gt;</span> <span class="fu">unique</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] LINESTRING      MULTILINESTRING
18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE</code></pre>
</div>
</div>
<p>The result is a mix of <code>LINESTRING</code> and <code>MULTILINESTRING</code>.</p>
<p>Since more than one geometry type is present, <code>roads_bmr</code> is cast to a single consistent type, <code>LINESTRING</code>, which <strong>spNetwork</strong> requires.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>roads_bmr <span class="ot">&lt;-</span> <span class="fu">st_cast</span>(roads_bmr, <span class="st">"LINESTRING"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The resulting <code>roads_bmr</code> is the road network used for the network-constrained kernel density estimation later in this exercise.</p>
</section>
</section>
<section id="feature-engineering" class="level2">
<h2 class="anchored" data-anchor-id="feature-engineering">7 Feature Engineering</h2>
<p><code>accidents_bmr</code> currently only has a single timestamp column, <code>incident_datetime</code>. This section derives temporal and contextual variables from it, which is needed to examine how accidents vary over time.</p>
<p><strong>1. Temporal Variables</strong></p>
<p>Temporal variables are extracted first:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>accidents_bmr <span class="ot">&lt;-</span> accidents_bmr <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month =</span> <span class="fu">month</span>(incident_datetime),</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">month_label =</span> <span class="fu">month</span>(incident_datetime, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">TRUE</span>),</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">day_of_week =</span> <span class="fu">wday</span>(incident_datetime, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">week_start =</span> <span class="dv">1</span>),</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">day_of_year =</span> <span class="fu">yday</span>(incident_datetime))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>2. Season</strong></p>
<p>Season is derived based on Thailand’s official three-season year - hot, rainy, and cool (<a href="https://thailand.go.th/event-detail/009_142">Government Public Relations Department</a>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>accidents_bmr <span class="ot">&lt;-</span> accidents_bmr <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">md =</span> <span class="fu">format</span>(incident_datetime, <span class="st">"%m-%d"</span>),</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">season =</span> <span class="fu">case_when</span>(</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>      md <span class="sc">&gt;=</span> <span class="st">"02-15"</span> <span class="sc">&amp;</span> md <span class="sc">&lt;</span> <span class="st">"05-15"</span> <span class="sc">~</span> <span class="st">"Hot"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>      md <span class="sc">&gt;=</span> <span class="st">"05-15"</span> <span class="sc">&amp;</span> md <span class="sc">&lt;</span> <span class="st">"10-15"</span> <span class="sc">~</span> <span class="st">"Rainy"</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Cool"</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>md)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>3. Peak Period</strong></p>
<p>Peak period is derived based on Bangkok’s known morning and evening rush hours. The exact cutoffs used here are a reasonable estimate rather than an official rule.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>accidents_bmr <span class="ot">&lt;-</span> accidents_bmr <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">hms =</span> <span class="fu">format</span>(incident_datetime, <span class="st">"%H:%M:%S"</span>),</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">peak_period =</span> <span class="fu">case_when</span>(</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>      hms <span class="sc">&gt;=</span> <span class="st">"07:00:00"</span> <span class="sc">&amp;</span> hms <span class="sc">&lt;=</span> <span class="st">"09:00:00"</span> <span class="sc">~</span> <span class="st">"Morning Peak"</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>      hms <span class="sc">&gt;=</span> <span class="st">"16:00:00"</span> <span class="sc">&amp;</span> hms <span class="sc">&lt;=</span> <span class="st">"19:00:00"</span> <span class="sc">~</span> <span class="st">"Evening Peak"</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Off-Peak"</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>hms)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>4. Songkran: “Seven Dangerous Days”</strong></p>
<p>Songkran’s “Seven Dangerous Days” is Thailand’s annual road-safety campaign, covering the week surrounding the Songkran New Year holiday, a period nationally recognised for a sharp rise in road accidents. Since this study covers 2022, the relevant campaign dates are 11 to 17 April that year (<a href="https://www.pressreader.com/thailand/the-phuket-news/20220422/281560884348253">The Phuket News</a>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>accidents_bmr <span class="ot">&lt;-</span> accidents_bmr <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">songkran_dangerous_days =</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>           incident_datetime <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2022-04-11"</span>) <span class="sc">&amp;</span> </span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>           incident_datetime <span class="sc">&lt;</span> <span class="fu">as.Date</span>(<span class="st">"2022-04-18"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Finally, unused columns are dropped: <code>province_th</code> (same information as <code>province_en</code>), <code>report_datetime</code> (reporting lag), and <code>route</code> (unused free text).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>accidents_bmr <span class="ot">&lt;-</span> accidents_bmr <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>province_th, <span class="sc">-</span>report_datetime, <span class="sc">-</span>route)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(accidents_bmr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,593
Columns: 21
$ acc_code                    &lt;dbl&gt; 5652876, 5484851, 6566824, 5485786, 549368…
$ incident_datetime           &lt;dttm&gt; 2022-01-01 01:00:00, 2022-01-01 02:30:00,…
$ province_en                 &lt;chr&gt; "Nonthaburi", "Samut Prakan", "Samut Sakho…
$ agency                      &lt;chr&gt; "department of highways", "department of h…
$ vehicle_type                &lt;chr&gt; "private/passenger car", "4-wheel pickup t…
$ presumed_cause              &lt;chr&gt; "speeding", "speeding", "driving under the…
$ accident_type               &lt;chr&gt; "rollover/fallen on straight road", "colli…
$ number_of_vehicles_involved &lt;dbl&gt; 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 6, 2, …
$ number_of_fatalities        &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ number_of_injuries          &lt;dbl&gt; 0, 0, 1, 0, 0, 1, 1, 0, 2, 2, 0, 2, 0, 1, …
$ weather_condition           &lt;chr&gt; "clear", "clear", "clear", "clear", "clear…
$ road_description            &lt;chr&gt; "straight road", "straight road", "straigh…
$ slope_description           &lt;chr&gt; "no slope", "no slope", "no slope", "no sl…
$ geometry                    &lt;POINT [m]&gt; POINT (665062.3 1540262), POINT (677…
$ month                       &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ month_label                 &lt;ord&gt; Jan, Jan, Jan, Jan, Jan, Jan, Jan, Jan, Ja…
$ day_of_week                 &lt;ord&gt; Sat, Sat, Sat, Sat, Sat, Sat, Sat, Sat, Sa…
$ day_of_year                 &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ season                      &lt;chr&gt; "Cool", "Cool", "Cool", "Cool", "Cool", "C…
$ peak_period                 &lt;chr&gt; "Off-Peak", "Off-Peak", "Off-Peak", "Off-P…
$ songkran_dangerous_days     &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …</code></pre>
</div>
</div>
</section>
<section id="spatial-point-pattern-analysis-sppa" class="level2">
<h2 class="anchored" data-anchor-id="spatial-point-pattern-analysis-sppa">8 Spatial Point Pattern Analysis (SPPA)</h2>
<p>This section applies spatial point pattern analysis (SPPA) using <strong>spatstat</strong> to quantify how road traffic accidents are distributed across the BMR, and to test whether the distribution departs from the Complete Spatial Randomness (CSR) hypothesis, which assumes that accidents occur independently and uniformly across the study area.</p>
<p>Three methods are applied:</p>
<ol type="1">
<li><p><strong>First-order analysis:</strong> Examine how accident intensity varies across the region, using kernel density estimation to identify areas of concentration</p></li>
<li><p><strong>Second-order analysis:</strong> Use Ripley’s G, F, K, and L functions to test whether accidents are more clustered, more regular, or consistent with CSR at varying distances</p></li>
<li><p><strong>Network-constrained analysis:</strong> Account for accidents being restricted to the road network rather than free to occur anywhere in planar space</p></li>
</ol>
<section id="constructing-the-point-pattern-objects" class="level3">
<h3 class="anchored" data-anchor-id="constructing-the-point-pattern-objects">8.1 Constructing the Point Pattern Objects</h3>
<p>Before SPPA can begin, the <code>sf</code> objects prepared above are converted into <code>ppp</code> (point pattern) and <code>owin</code> (observation window) objects, so that they are in the formats <strong>spatstat</strong> works with.</p>
<p>The observation window is built first, from <code>adm2_bmr</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>adm2_owin <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(adm2_bmr)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>adm2_owin</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>window: polygonal boundary
enclosing rectangle: [565545.8, 743060.3] x [1468709.7, 1599777.2] units</code></pre>
</div>
</div>
<p>The point pattern is then built from <code>accidents_bmr</code>, using the above observation window:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>accidents_ppp <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(accidents_bmr, <span class="at">W =</span> adm2_owin)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>accidents_ppp</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern: 3593 points
Mark variables: 
   acc_code incident_datetime province_en agency vehicle_type presumed_cause 
accident_type number_of_vehicles_involved number_of_fatalities 
number_of_injuries weather_condition road_description slope_description month 
month_label day_of_week day_of_year season peak_period songkran_dangerous_days
window: polygonal boundary
enclosing rectangle: [565545.8, 743060.3] x [1468709.7, 1599777.2] units</code></pre>
</div>
</div>
<p>Next, the point pattern is checked for duplicated points, since accidents recorded at identical coordinates are treated differently by <strong>spatstat</strong> than by <strong>sf</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">duplicated</span>(accidents_ppp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Since no duplicated points are found, <code>rjitter()</code> will not be needed.</p>
</div>
</div>
<p><code>accidents_ppp</code> and <code>adm2</code>_owin are rescaled from metres to kilometres as this keeps the intensity and area readable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>accidents_ppp_km <span class="ot">&lt;-</span> <span class="fu">rescale</span>(accidents_ppp, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>adm2_owin_km <span class="ot">&lt;-</span> <span class="fu">rescale</span>(adm2_owin, <span class="dv">1000</span>, <span class="st">"km"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The rescaled point pattern is plotted against its window, confirming the points fall within the study area:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">unmark</span>(accidents_ppp_km), <span class="at">main =</span> <span class="st">"Road Accidents in the BMR (2022)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="reference" class="level2">
<h2 class="anchored" data-anchor-id="reference">Reference</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>