{
  "hash": "9f619aaa244b7a77d1119c75f89ccb6e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Geospatial Analytics for Public Safety\"\nsubtitle: \"Spatial and Spatio-Temporal Point Pattern Analysis of Road Traffic Accidents in the Bangkok Metropolitan Region\"\ndate: \"September 19, 2026\"\ndate-modified: \"last-modified\"\nformat: html\nexecute:\n  echo: true\n  eval: true\n  message: false\n  warning: false\n  freeze: true\neditor: visual\n---\n\n## 1 Overview\n\nPublic safety planning increasingly relies on location-based evidence to identify where and when incidents concentrate, so that enforcement, engineering, and policy responses can be targeted rather than applied uniformly across a region. Road traffic accidents are a point event well suited to this type of analysis: each incident carries a location and a time, and the accumulated pattern of incidents can reveal whether risk is randomly scattered or systematically concentrated in identifiable places and periods.\n\nThis exercise applies spatial and spatio-temporal point pattern analysis to road traffic accident data for the [Bangkok Metropolitan Region (BMR)](https://en.wikipedia.org/wiki/Bangkok_Metropolitan_Region), Thailand, covering Bangkok and the five adjacent provinces of Nonthaburi, Nakhon Pathom, Pathum Thani, Samut Prakan, and Samut Sakhon.\n\n## 2 Analytical Questions\n\n1.  How is the intensity of road traffic accidents distributed across space and time within the BMR?\n2.  Do accidents exhibit statistically significant spatial and spatio-temporal clustering, beyond what would be expected under complete spatial randomness?\n3.  Does accounting for the road network materially change the interpretation of accident concentration, compared to treating accidents as freely distributed in planar space?\n4.  What do the resulting patterns imply for public safety planning and resource allocation within the region?\n\n## 3 The Data\n\nThree datasets are used in this exercise:\n\n| Dataset | Description | Format | Source | Date Accessed |\n|---------------|---------------|---------------|---------------|---------------|\n| Thailand Road Accident (2019 to 2022) | Accident-level records with location, timing, severity, and contributing-factor fields, sourced from the Ministry of Transport's TRAMS dashboard. **Only the 2022 subset is used for this study.** | CSV | [Kaggle](https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022) | 20 Sep 2026 |\n| Thailand Administrative Boundaries, ADM2 | District-level administrative boundaries for Thailand | GeoJSON | [geoBoundaries](https://www.geoboundaries.org) | 20 Sep 2026 |\n| Thailand Road Network (OpenStreetMap extract) | Line-based road network for Thailand, classified by highway type under the `fclass` field | Shapefile | [Geofabrik](https://download.geofabrik.de/asia/thailand.html) | 20 Sep 2026 |\n\n## 4 Installing and Loading the R Packages\n\nThe following R packages are used across this exercise:\n\n| Package | Purpose | Use Case in This Exercise |\n|------------------------|------------------------|------------------------|\n| **tidyverse** | Collection of packages for data import, manipulation, and visualisation | Importing, cleaning, and transforming the accident dataset |\n| **sf** | Imports, manages, and processes vector-based geospatial data | Handling the administrative boundary and road network data, and constructing spatial point objects from the accident coordinates |\n| **spatstat** | Toolkit for spatial point pattern analysis | First-order (KDE, quadrat) and second-order (G, F, K, L functions) analysis of accident intensity and clustering |\n| **sparr** | Kernel estimation of spatial and spatio-temporal densities | Spatio-temporal KDE of accident intensity across months in 2022 |\n| **stpp** | Analysis of second-order properties of spatio-temporal point processes | Testing for space-time interaction beyond what spatial and temporal clustering alone would predict |\n| **spNetwork** | Spatial analysis constrained to a network | Network-constrained kernel density estimation (NKDE) of accidents along the road network |\n| **tmap** | Static and interactive thematic mapping | Choropleth maps, KDE surfaces, and accident point maps throughout the report |\n| **knitr** | Dynamic report generation | Rendering tables and controlling code chunk output |\n| **plotly** | Creates interactive visualisations | Building interactive charts for Exploratory Data Analysis |\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, sf, spatstat, sparr, stpp, \n               spNetwork, tmap, knitr, plotly)\n```\n:::\n\n\n## 5 Reproducibility\n\nA fixed seed value of 123 is set for reproducibility of any simulation-based procedure used later in this exercise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n```\n:::\n\n\n## 6 Importing and Preparing the Data\n\nThis section imports and prepares each of the three datasets described above. The study area for this exercise is the Bangkok Metropolitan Region (BMR), operationalised at the district (ADM2) level, and the study period is restricted to 2022.\n\n### 6.1 Thailand Road Accident Data\n\nThe accident dataset is imported using *read_csv()* of the **readr** package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrdacc <- read_csv(\"data/thai_road_accident_2019_2022.csv\")\n```\n:::\n\n\nNull values are checked across every column:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(rdacc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   acc_code           incident_datetime \n                          0                           0 \n            report_datetime                 province_th \n                          0                           0 \n                province_en                      agency \n                          0                           0 \n                      route                vehicle_type \n                          0                           0 \n             presumed_cause               accident_type \n                          0                           0 \nnumber_of_vehicles_involved        number_of_fatalities \n                          0                           0 \n         number_of_injuries           weather_condition \n                          0                           0 \n                   latitude                   longitude \n                        359                         359 \n           road_description           slope_description \n                          0                           0 \n```\n\n\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\nOf the 359 rows with missing coordinates, 350 are attributed to a single agency, the Expressway Authority of Thailand. The other two agencies, Department of Highways and Department of Rural Roads, have almost none missing. The affected rows are concentrated in Bangkok and in the 2021 to 2022 period. These rows cannot be placed spatially, so they are dropped from the point pattern analysis. As a result, accidents attributed to the Expressway Authority, largely Bangkok's controlled-access expressway network, are undercounted relative to the other two agencies.\n:::\n\nExact duplicate rows are checked next:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(duplicated(rdacc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nThe set of provinces represented in the data is inspected, since only accidents within the six BMR provinces are relevant to this exercise:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(unique(rdacc$province_en))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Amnat Charoen\"            \"Ang Thong\"               \n [3] \"Bangkok\"                  \"buogkan\"                 \n [5] \"Buri Ram\"                 \"Chachoengsao\"            \n [7] \"Chai Nat\"                 \"Chaiyaphum\"              \n [9] \"Chanthaburi\"              \"Chiang Mai\"              \n[11] \"Chiang Rai\"               \"Chon Buri\"               \n[13] \"Chumphon\"                 \"Kalasin\"                 \n[15] \"Kamphaeng Phet\"           \"Kanchanaburi\"            \n[17] \"Khon Kaen\"                \"Krabi\"                   \n[19] \"Lampang\"                  \"Lamphun\"                 \n[21] \"Loburi\"                   \"Loei\"                    \n[23] \"Mae Hong Son\"             \"Maha Sarakham\"           \n[25] \"Mukdahan\"                 \"Nakhon Nayok\"            \n[27] \"Nakhon Pathom\"            \"Nakhon Phanom\"           \n[29] \"Nakhon Ratchasima\"        \"Nakhon Sawan\"            \n[31] \"Nakhon Si Thammarat\"      \"Nan\"                     \n[33] \"Narathiwat\"               \"Nong Bua Lam Phu\"        \n[35] \"Nong Khai\"                \"Nonthaburi\"              \n[37] \"Pathum Thani\"             \"Pattani\"                 \n[39] \"Phangnga\"                 \"Phatthalung\"             \n[41] \"Phayao\"                   \"Phetchabun\"              \n[43] \"Phetchaburi\"              \"Phichit\"                 \n[45] \"Phitsanulok\"              \"Phra Nakhon Si Ayutthaya\"\n[47] \"Phrae\"                    \"Phuket\"                  \n[49] \"Prachin Buri\"             \"Prachuap Khiri Khan\"     \n[51] \"Ranong\"                   \"Ratchaburi\"              \n[53] \"Rayong\"                   \"Roi Et\"                  \n[55] \"Sa Kaeo\"                  \"Sakon Nakhon\"            \n[57] \"Samut Prakan\"             \"Samut Sakhon\"            \n[59] \"Samut Songkhram\"          \"Saraburi\"                \n[61] \"Satun\"                    \"Si Sa Ket\"               \n[63] \"Sing Buri\"                \"Songkhla\"                \n[65] \"Sukhothai\"                \"Suphan Buri\"             \n[67] \"Surat Thani\"              \"Surin\"                   \n[69] \"Tak\"                      \"Trang\"                   \n[71] \"Trat\"                     \"Ubon Ratchathani\"        \n[73] \"Udon Thani\"               \"unknown\"                 \n[75] \"Uthai Thani\"              \"Uttaradit\"               \n[77] \"Yala\"                     \"Yasothon\"                \n```\n\n\n:::\n:::\n\n\nThe six BMR province names are confirmed to appear exactly as expected in the list above (Bangkok, Nonthaburi, Nakhon Pathom, Pathum Thani, Samut Prakan, Samut Sakhon).\n\nThe dataset is filtered to the study area (BMR) and study period (2022), and limited to rows with valid coordinates. It is then converted into a spatial point object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_provinces <- c(\"Bangkok\", \"Nonthaburi\", \"Nakhon Pathom\", \n                   \"Pathum Thani\", \"Samut Prakan\", \"Samut Sakhon\")\n\naccidents_bmr <- rdacc %>%\n  filter(province_en %in% bmr_provinces,\n         year(incident_datetime) == 2022,\n         !is.na(latitude), !is.na(longitude)) %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326) %>%\n  st_transform(crs = 32647)\n```\n:::\n\n\n::: callout-note\n- [crs = 4326](https://epsg.io/4326) labels the coordinates as WGS84 decimal degrees\n- [crs = 32647](crs%20=%2032647) then reprojects them into UTM Zone 47N (metres). EPSG:32647 specifically covers 96°E to 102°E, the zone the BMR provinces fall within; this reprojection is needed for the distance- and area-based methods used later.\n:::\n\n### 6.2 Administrative Boundaries: Bangkok Metropolitan Region (BMR)\n\nThailand's administrative boundaries run from country (ADM0), through province (ADM1), district (ADM2), to sub-district (ADM3).\n\nThis exercise uses both ADM1 and ADM2: ADM1 identifies the six provinces that make up the BMR by name, and ADM2 supplies the actual study area boundary at finer district resolution, needed later for the network-constrained analysis. ADM2's own attribute table does not record which province each district belongs to, so the two levels are combined through a spatial join.\n\nADM1 is imported first, since it supplies the province names needed to define the BMR.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntha_adm1 <- st_read(\"data/geoBoundaries-THA-ADM1.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `geoBoundaries-THA-ADM1' from data source \n  `C:\\yxlinn\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex01\\data\\geoBoundaries-THA-ADM1.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 77 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34381 ymin: 5.612851 xmax: 105.6368 ymax: 20.46483\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(tha_adm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 99.08799 ymin: 13.17157 xmax: 104.3559 ymax: 19.73551\nGeodetic CRS:  WGS 84\n                  shapeName shapeISO                 shapeID shapeGroup\n1           Roi Et Province    TH-45 36821470B96343765829948        THA\n2           Phayao Province    TH-56 36821470B12194119812739        THA\n3     Nakhon Sawan Province    TH-60 36821470B58837026258254        THA\n4 Nong Bua Lam Phu Province    TH-39 36821470B48254980905782        THA\n5     Chachoengsao Province    TH-24 36821470B91271468807469        THA\n6            Surin Province    TH-32 36821470B33660676013176        THA\n  shapeType                       geometry\n1      ADM1 MULTIPOLYGON (((103.5111 16...\n2      ADM1 MULTIPOLYGON (((99.68719 19...\n3      ADM1 MULTIPOLYGON (((99.08899 15...\n4      ADM1 MULTIPOLYGON (((102.0808 17...\n5      ADM1 MULTIPOLYGON (((100.849 13....\n6      ADM1 MULTIPOLYGON (((103.4048 15...\n```\n\n\n:::\n:::\n\n\nThe full list of province names is checked before filtering:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(unique(tha_adm1$shapeName))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Amnat Charoen Province\"            \"Ang Thong Province\"               \n [3] \"Bangkok\"                           \"Bueng Kan Province\"               \n [5] \"Buri Ram Province\"                 \"Chachoengsao Province\"            \n [7] \"Chai Nat Province\"                 \"Chaiyaphum Province\"              \n [9] \"Chanthaburi Province\"              \"Chiang Mai Province\"              \n[11] \"Chiang Rai Province\"               \"Chon Buri Province\"               \n[13] \"Chumphon Province\"                 \"Kalasin\"                          \n[15] \"Kamphaeng Phet Province\"           \"Kanchanaburi Province\"            \n[17] \"Khon Kaen Province\"                \"Krabi Province\"                   \n[19] \"Lampang Province\"                  \"Lamphun Province\"                 \n[21] \"Loei Province\"                     \"Lopburi Province\"                 \n[23] \"Mae Hong Son Province\"             \"Maha Sarakham Province\"           \n[25] \"Mukdahan Province\"                 \"Nakhon Nayok Province\"            \n[27] \"Nakhon Pathom Province\"            \"Nakhon Phanom Province\"           \n[29] \"Nakhon Ratchasima Province\"        \"Nakhon Sawan Province\"            \n[31] \"Nakhon Si Thammarat Province\"      \"Nan Province\"                     \n[33] \"Narathiwat Province\"               \"Nong Bua Lam Phu Province\"        \n[35] \"Nong Khai Province\"                \"Nonthaburi Province\"              \n[37] \"Pathum Thani Province\"             \"Pattani Province\"                 \n[39] \"Phangnga Province\"                 \"Phatthalung Province\"             \n[41] \"Phayao Province\"                   \"Phetchabun Province\"              \n[43] \"Phetchaburi Province\"              \"Phichit Province\"                 \n[45] \"Phitsanulok Province\"              \"Phra Nakhon Si Ayutthaya Province\"\n[47] \"Phrae Province\"                    \"Phuket Province\"                  \n[49] \"Prachin Buri Province\"             \"Prachuap Khiri Khan Province\"     \n[51] \"Ranong Province\"                   \"Ratchaburi Province\"              \n[53] \"Rayong Province\"                   \"Roi Et Province\"                  \n[55] \"Sa Kaeo Province\"                  \"Sakon Nakhon Province\"            \n[57] \"Samut Prakan Province\"             \"Samut Sakhon Province\"            \n[59] \"Samut Songkhram Province\"          \"Saraburi Province\"                \n[61] \"Satun Province\"                    \"Si Sa Ket Province\"               \n[63] \"Sing Buri Province\"                \"Songkhla Province\"                \n[65] \"Sukhothai Province\"                \"Suphan Buri Province\"             \n[67] \"Surat Thani Province\"              \"Surin Province\"                   \n[69] \"Tak Province\"                      \"Trang Province\"                   \n[71] \"Trat Province\"                     \"Ubon Ratchathani Province\"        \n[73] \"Udon Thani Province\"               \"Uthai Thani Province\"             \n[75] \"Uttaradit Province\"                \"Yala Province\"                    \n[77] \"Yasothon Province\"                \n```\n\n\n:::\n:::\n\n\nNext, ADM2 is imported to supply the actual study area boundary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntha_adm2 <- st_read(\"data/geoBoundaries-THA-ADM2.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `geoBoundaries-THA-ADM2' from data source \n  `C:\\yxlinn\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex01\\data\\geoBoundaries-THA-ADM2.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 928 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(tha_adm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 98.6116 ymin: 6.471538 xmax: 104.0843 ymax: 17.82245\nGeodetic CRS:  WGS 84\n      shapeName shapeISO                 shapeID shapeGroup shapeType\n1   Akat Amnuai          78962969B83463915016953        THA      ADM2\n2       Amphawa          78962969B68169586280131        THA      ADM2\n3       Ao Luek          78962969B54777225393770        THA      ADM2\n4 Aranyaprathet          78962969B18658138340114        THA      ADM2\n5      At Samat          78962969B71289419444255        THA      ADM2\n6         Bacho          78962969B22586560209583        THA      ADM2\n                        geometry\n1 MULTIPOLYGON (((104.0122 17...\n2 MULTIPOLYGON (((100.0144 13...\n3 MULTIPOLYGON (((98.69051 8....\n4 MULTIPOLYGON (((102.5356 13...\n5 MULTIPOLYGON (((103.8999 15...\n6 MULTIPOLYGON (((101.7093 6....\n```\n\n\n:::\n:::\n\n\n::: callout-note\n`tha_adm2` has 928 features and five attribute fields: shapeName, shapeISO, shapeID, shapeGroup, and shapeType. None of the fields represent a parent province. The BMR district set therefore cannot be filtered by attribute and is derived spatially against ADM1.\n:::\n\nBoth boundaries are reprojected to EPSG:32647.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntha_adm1 <- st_transform(tha_adm1, crs = 32647)\ntha_adm2 <- st_transform(tha_adm2, crs = 32647)\n```\n:::\n\n\nThe six BMR provinces are filtered out of ADM1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_provinces_adm1 <- c(\"Bangkok\", \n                        \"Nonthaburi Province\",\n                        \"Nakhon Pathom Province\",\n                        \"Pathum Thani Province\",\n                        \"Samut Prakan Province\",\n                        \"Samut Sakhon Province\")\n\nadm1_bmr <- tha_adm1 %>%\n  filter(shapeName %in% bmr_provinces_adm1) %>%\n  rename(province_name = shapeName)\n\nnrow(adm1_bmr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n:::\n\n\n::: callout-note\n`shapeName` is renamed to `province_name` to avoid a duplicate column when joined to `tha_adm2`, which carries its own `shapeName` field for district names.\n:::\n\nEach ADM2 district is then assigned to whichever ADM1 province it overlaps most with, and only those districts assigned to one of the six BMR provinces are kept.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadm2_bmr <- st_join(tha_adm2, adm1_bmr, \n                    join = st_intersects, \n                    largest = TRUE) %>% \n  filter(!is.na(province_name)) %>%\n  select(shapeName, province_name, geometry)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadm2_bmr %>%\n  st_drop_geometry() %>%\n  count(province_name)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           province_name  n\n1                Bangkok 52\n2 Nakhon Pathom Province 11\n3    Nonthaburi Province  7\n4  Pathum Thani Province 14\n5  Samut Prakan Province  8\n6  Samut Sakhon Province  5\n```\n\n\n:::\n:::\n\n\nThe resulting `adm2_bmr` is the study area boundary used for the remainder of this exercise.\n\nAs a visual check, the boundary is plotted and coloured by province. This shows whether the districts form one connected region, or whether any district ended up misplaced or disconnected, something the count above could not reveal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(adm2_bmr) +\n  tm_polygons(fill = \"province_name\",\n              fill.legend = tm_legend(title = \"Province\", na.show = FALSE)) +\n  tm_layout(main.title = \"BMR Study Area by Province\",\n            main.title.position = \"center\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n### 6.3 Road Network\n\nThe road network is imported and inspected:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads <- st_read(\"data/gis_osm_roads_free_1.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `gis_osm_roads_free_1' from data source \n  `C:\\yxlinn\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex01\\data\\gis_osm_roads_free_1.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 2930769 features and 10 fields\nGeometry type: LINESTRING\nDimension:     XY\nBounding box:  xmin: 97.31354 ymin: 5.643645 xmax: 105.6481 ymax: 20.47168\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(roads)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,930,769\nColumns: 11\n$ osm_id   <chr> \"4270622\", \"4828442\", \"4828443\", \"4828444\", \"4828446\", \"85607…\n$ code     <int> 5122, 5122, 5122, 5122, 5122, 5122, 5122, 5122, 5122, 5153, 5…\n$ fclass   <chr> \"residential\", \"residential\", \"residential\", \"residential\", \"…\n$ name     <chr> \"ถนนศิริมังคลาจารย์ ซอย1\", \"Soi Ruam- U-Thit\", \"Soi Ruam- U-Thit\"…\n$ ref      <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ oneway   <chr> \"B\", \"B\", \"B\", \"B\", \"B\", \"B\", \"F\", \"B\", \"F\", \"B\", \"F\", \"F\", \"…\n$ maxspeed <int> 0, 0, 0, 0, 0, 30, 30, 0, 0, 0, 50, 0, 60, 0, 0, 60, 60, 60, …\n$ layer    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 2…\n$ bridge   <chr> \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"T\", \"…\n$ tunnel   <chr> \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"…\n$ geometry <LINESTRING [°]> LINESTRING (98.97274 18.796..., LINESTRING (98.341…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(roads)$input\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"WGS 84\"\n```\n\n\n:::\n:::\n\n\nThe highway classification is inspected via the `fclass` field:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(unique(roads$fclass))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"bridleway\"      \"busway\"         \"cycleway\"       \"footway\"       \n [5] \"living_street\"  \"motorway\"       \"motorway_link\"  \"path\"          \n [9] \"pedestrian\"     \"primary\"        \"primary_link\"   \"residential\"   \n[13] \"secondary\"      \"secondary_link\" \"service\"        \"steps\"         \n[17] \"tertiary\"       \"tertiary_link\"  \"track\"          \"track_grade1\"  \n[21] \"track_grade2\"   \"track_grade3\"   \"track_grade4\"   \"track_grade5\"  \n[25] \"trunk\"          \"trunk_link\"     \"unclassified\"   \"unknown\"       \n```\n\n\n:::\n:::\n\n\nThe road network is reprojected to EPSG:32647.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads <- st_transform(roads, crs = 32647)\n```\n:::\n\n\nFor the purpose of this study, the network is filtered to the intercity highway classes based on the [WikiProject Thailand highway classification convention](https://wiki.openstreetmap.org/wiki/Thailand/Conventions).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhighway_types <- c(\"motorway\", \"motorway_link\", \n                   \"trunk\",\"trunk_link\", \n                   \"primary\", \"primary_link\",\n                   \"secondary\", \"secondary_link\",\n                   \"tertiary\", \"tertiary_link\", \n                   \"unclassified\")\n\nroads_filtered <- roads %>%\n  filter(fclass %in% highway_types)\n```\n:::\n\n\n::: callout-note\nThe 28 `fclass` values include a `_link` variant for five of the six target classes, representing ramps and interchange connectors rather than a separate road type. These are kept alongside their base class, since dropping them would leave a gap at every interchange, breaking the network needed for the network-constrained analysis later. The rest are excluded as non-vehicular, local, or unclassifiable.\n:::\n\nThe filtered network is then clipped to the BMR study area:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bmr <- st_intersection(roads_filtered, adm2_bmr)\n```\n:::\n\n\nClipping lines against polygons with `st_intersection()` can change geometry types. For example, a line that only touches a polygon boundary at a single point can come out as a point instead of a line. Therefore, the geometry types present in `roads_bmr` are checked.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_geometry_type(roads_bmr) |> unique()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] LINESTRING      MULTILINESTRING\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n:::\n\n\nThe result is a mix of `LINESTRING` and `MULTILINESTRING`.\n\nSince more than one geometry type is present, `roads_bmr` is cast to a single consistent type, `LINESTRING`, which **spNetwork** requires.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bmr <- st_cast(roads_bmr, \"LINESTRING\")\n```\n:::\n\n\nThe resulting `roads_bmr` is the road network used for the network-constrained kernel density estimation later in this exercise.\n\n## 7 Feature Engineering\n\n`accidents_bmr` currently only has a single timestamp column, `incident_datetime`. This section derives temporal and contextual variables from it, which is needed to examine how accidents vary over time.\n\n### 7.1 Temporal Variables\n\nTemporal variables are extracted first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_bmr <- accidents_bmr %>%\n  mutate(month = month(incident_datetime),\n         month_label = month(incident_datetime, label = TRUE, abbr = TRUE),\n         day_of_week = wday(incident_datetime, label = TRUE, week_start = 1),\n         day_of_year = yday(incident_datetime))\n```\n:::\n\n\n### 7.2 Season\n\nSeason is derived based on Thailand's official three-season year - hot, rainy, and cool ([Government Public Relations Department](https://thailand.go.th/event-detail/009_142)):\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_bmr <- accidents_bmr %>%\n  mutate(\n    md = format(incident_datetime, \"%m-%d\"),\n    season = case_when(\n      md >= \"02-15\" & md < \"05-15\" ~ \"Hot\",\n      md >= \"05-15\" & md < \"10-15\" ~ \"Rainy\",\n      TRUE ~ \"Cool\"\n    )\n  ) %>%\n  select(-md)\n```\n:::\n\n\n### 7.3 Peak Period\n\nPeak period is derived based on Bangkok's known morning and evening rush hours. The exact cutoffs used here are a reasonable estimate rather than an official rule.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_bmr <- accidents_bmr %>%\n  mutate(\n    hms = format(incident_datetime, \"%H:%M:%S\"),\n    peak_period = case_when(\n      hms >= \"07:00:00\" & hms <= \"09:00:00\" ~ \"Morning Peak\",\n      hms >= \"16:00:00\" & hms <= \"19:00:00\" ~ \"Evening Peak\",\n      TRUE ~ \"Off-Peak\"\n    )\n  ) %>%\n  select(-hms)\n```\n:::\n\n\n### 7.4 Songkran: \"Seven Dangerous Days\"\n\nSongkran's \"Seven Dangerous Days\" is Thailand's annual road-safety campaign, covering the week surrounding the Songkran New Year holiday, a period nationally recognised for a sharp rise in road accidents. Since this study covers 2022, the relevant campaign dates are 11 to 17 April that year ([The Phuket News](https://www.pressreader.com/thailand/the-phuket-news/20220422/281560884348253)).\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_bmr <- accidents_bmr %>% \n  mutate(songkran_dangerous_days = \n           incident_datetime >= as.Date(\"2022-04-11\") & \n           incident_datetime < as.Date(\"2022-04-18\"))\n```\n:::\n\n\nFinally, unused columns are dropped: `province_th` (same information as `province_en`), `report_datetime` (reporting lag), and `route` (unused free text).\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_bmr <- accidents_bmr %>%\n  select(-province_th, -report_datetime, -route)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(accidents_bmr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,593\nColumns: 21\n$ acc_code                    <dbl> 5652876, 5484851, 6566824, 5485786, 549368…\n$ incident_datetime           <dttm> 2022-01-01 01:00:00, 2022-01-01 02:30:00,…\n$ province_en                 <chr> \"Nonthaburi\", \"Samut Prakan\", \"Samut Sakho…\n$ agency                      <chr> \"department of highways\", \"department of h…\n$ vehicle_type                <chr> \"private/passenger car\", \"4-wheel pickup t…\n$ presumed_cause              <chr> \"speeding\", \"speeding\", \"driving under the…\n$ accident_type               <chr> \"rollover/fallen on straight road\", \"colli…\n$ number_of_vehicles_involved <dbl> 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 6, 2, …\n$ number_of_fatalities        <dbl> 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ number_of_injuries          <dbl> 0, 0, 1, 0, 0, 1, 1, 0, 2, 2, 0, 2, 0, 1, …\n$ weather_condition           <chr> \"clear\", \"clear\", \"clear\", \"clear\", \"clear…\n$ road_description            <chr> \"straight road\", \"straight road\", \"straigh…\n$ slope_description           <chr> \"no slope\", \"no slope\", \"no slope\", \"no sl…\n$ geometry                    <POINT [m]> POINT (665062.3 1540262), POINT (677…\n$ month                       <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ month_label                 <ord> Jan, Jan, Jan, Jan, Jan, Jan, Jan, Jan, Ja…\n$ day_of_week                 <ord> Sat, Sat, Sat, Sat, Sat, Sat, Sat, Sat, Sa…\n$ day_of_year                 <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ season                      <chr> \"Cool\", \"Cool\", \"Cool\", \"Cool\", \"Cool\", \"C…\n$ peak_period                 <chr> \"Off-Peak\", \"Off-Peak\", \"Off-Peak\", \"Off-P…\n$ songkran_dangerous_days     <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …\n```\n\n\n:::\n:::\n\n\n## 8 Exploratory Data Analysis (EDA)\n\nThis section conducts an Exploratory Data Analysis (EDA) to visualise the distribution of road accidents in the BMR in 2022. The findings identified will support the public safety discussion by providing relevant evidence about accident circumstances.\n\n### 8.1 Overview Map\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(adm2_bmr) +\n  tm_polygons(fill = \"province_name\", fill.legend = tm_legend(title = \"Province\", na.show = FALSE)) +\ntm_shape(roads_bmr) +\n  tm_lines(col = \"darkgreen\", lwd = 1) +\ntm_shape(accidents_bmr) +\n  tm_dots(fill = \"red\", size = 0.05) +\ntm_layout(main.title = \"Road Traffic Accidents in the BMR (2022)\", main.title.position = \"center\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\n- Accident points are concentrated along the road network across the BMR, rather than scattered away from mapped roads.\n- Accident density appears visibly higher in the central portion of the study area, spanning parts of Bangkok, Nonthaburi, and Samut Prakan, compared to the northern part of Pathum Thani and the western part of Nakhon Pathom.\n- The road network itself appears denser in the central and southern portions of the study area, with a comparatively sparser network in the northern part of Pathum Thani.\n:::\n\n### 8.2 Accidents by Month and Season\n\nAccident counts are aggregated by `month_label` and `season`, highlighting how many accidents happen each month.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_by_month <- accidents_bmr %>%\n  st_drop_geometry() %>%\n  count(month_label, season)\n```\n:::\n\n\nThe result is plotted as a grouped bar chart using **plotly**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_ly(accidents_by_month, x = ~month_label, y = ~n, color = ~season,\n        colors = c(\"Cool\" = \"lightblue\", \"Hot\" = \"red3\", \"Rainy\" = \"royalblue3\"),\n        type = \"bar\") %>%\n  layout(title = \"Accidents by Month, Coloured by Season\",\n         xaxis = list(title = \"Month\"), yaxis = list(title = \"Number of Accidents\"),\n         barmode = \"stack\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-9eceb20dc2a931752ae4\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-9eceb20dc2a931752ae4\">{\"x\":{\"visdat\":{\"65f03a27105a\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"65f03a27105a\",\"attrs\":{\"65f03a27105a\":{\"x\":{},\"y\":{},\"color\":{},\"colors\":[\"lightblue\",\"red3\",\"royalblue3\"],\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"bar\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"Accidents by Month, Coloured by Season\",\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Month\",\"type\":\"category\",\"categoryorder\":\"array\",\"categoryarray\":[\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\",\"Jul\",\"Aug\",\"Sept\",\"Oct\",\"Nov\",\"Dec\"]},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Number of Accidents\"},\"barmode\":\"stack\",\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[\"Jan\",\"Feb\",\"Oct\",\"Nov\",\"Dec\"],\"y\":[277,111,214,367,369],\"type\":\"bar\",\"name\":\"Cool\",\"marker\":{\"color\":\"rgba(173,216,230,1)\",\"line\":{\"color\":\"rgba(173,216,230,1)\"}},\"textfont\":{\"color\":\"rgba(173,216,230,1)\"},\"error_y\":{\"color\":\"rgba(173,216,230,1)\"},\"error_x\":{\"color\":\"rgba(173,216,230,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[\"Feb\",\"Mar\",\"Apr\",\"May\"],\"y\":[100,244,332,120],\"type\":\"bar\",\"name\":\"Hot\",\"marker\":{\"color\":\"rgba(205,0,0,1)\",\"line\":{\"color\":\"rgba(205,0,0,1)\"}},\"textfont\":{\"color\":\"rgba(205,0,0,1)\"},\"error_y\":{\"color\":\"rgba(205,0,0,1)\"},\"error_x\":{\"color\":\"rgba(205,0,0,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[\"May\",\"Jun\",\"Jul\",\"Aug\",\"Sept\",\"Oct\"],\"y\":[122,241,312,324,280,180],\"type\":\"bar\",\"name\":\"Rainy\",\"marker\":{\"color\":\"rgba(58,95,205,1)\",\"line\":{\"color\":\"rgba(58,95,205,1)\"}},\"textfont\":{\"color\":\"rgba(58,95,205,1)\"},\"error_y\":{\"color\":\"rgba(58,95,205,1)\"},\"error_x\":{\"color\":\"rgba(58,95,205,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\n- October, November, and December (Cool season) show the highest total accidents of the year, with October being the highest.\n- April (Hot season) also shows a high total accident count, standing out clearly above the other Hot season months.\n- February show comparatively lower total accidents than most other months.\n- The Rainy season months (June to September) show generally high and relatively consistent total accidents across that stretch, without a sharp peak or dip within the season.\n- The Hot season (mid-February to mid-May) shows more variation in total accidents between its months than the Rainy or Cool seasons, ranging from one of the lowest totals (February) to one of the highest (April).\n:::\n\n#### 8.2.1 Event: Songkran Festival\n\nThis subsection examines the impact of the Songkran festival on road accidents in April, a period known for increased travel and correspondingly elevated road risk. `songkran_dangerous_days`, derived in Feature Engineering, flags accidents falling within the 11 to 17 April Seven Dangerous Days window. Since this period covers 7 days against 23 remaining days in April, the average daily accident rate is compared rather than raw totals, to avoid a comparison biased toward whichever side has more days.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsongkran_comparison <- accidents_bmr %>%\n  st_drop_geometry() %>%\n  filter(month == 4) %>%\n  count(songkran_dangerous_days) %>%\n  mutate(\n    days_count = if_else(songkran_dangerous_days, 7, 30 - 7),\n    average_daily_accidents = n / days_count,\n    label = if_else(songkran_dangerous_days, \"Songkran (11 to 17 Apr)\", \"Rest of April\")\n  )\n\nplot_ly(songkran_comparison, x = ~label, y = ~average_daily_accidents, color = ~label,\n        colors = c(\"Songkran (11 to 17 Apr)\" = \"tomato1\", \"Rest of April\" = \"royalblue3\"),\n        type = \"bar\") %>%\n  layout(title = \"Average Daily Accident Rate: Songkran vs Rest of April\",\n         xaxis = list(title = \"Period\"), yaxis = list(title = \"Average Accidents per Day\"),\n         showlegend = FALSE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-f30d7598595affc4f25a\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f30d7598595affc4f25a\">{\"x\":{\"visdat\":{\"65f05f084f54\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"65f05f084f54\",\"attrs\":{\"65f05f084f54\":{\"x\":{},\"y\":{},\"color\":{},\"colors\":[\"tomato1\",\"royalblue3\"],\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"bar\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"Average Daily Accident Rate: Songkran vs Rest of April\",\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Period\",\"type\":\"category\",\"categoryorder\":\"array\",\"categoryarray\":[\"Rest of April\",\"Songkran (11 to 17 Apr)\"]},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Average Accidents per Day\"},\"showlegend\":false,\"hovermode\":\"closest\"},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[\"Rest of April\"],\"y\":[8.7826086956521738],\"type\":\"bar\",\"name\":\"Rest of April\",\"marker\":{\"color\":\"rgba(58,95,205,1)\",\"line\":{\"color\":\"rgba(58,95,205,1)\"}},\"textfont\":{\"color\":\"rgba(58,95,205,1)\"},\"error_y\":{\"color\":\"rgba(58,95,205,1)\"},\"error_x\":{\"color\":\"rgba(58,95,205,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[\"Songkran (11 to 17 Apr)\"],\"y\":[18.571428571428573],\"type\":\"bar\",\"name\":\"Songkran (11 to 17 Apr)\",\"marker\":{\"color\":\"rgba(255,99,71,1)\",\"line\":{\"color\":\"rgba(255,99,71,1)\"}},\"textfont\":{\"color\":\"rgba(255,99,71,1)\"},\"error_y\":{\"color\":\"rgba(255,99,71,1)\"},\"error_x\":{\"color\":\"rgba(255,99,71,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\n- The average daily accident rate during the Songkran Seven Dangerous Days (11 to 17 April) is substantially higher than the average daily rate for the rest of April, more than double.\n- This is consistent with Songkran being a period of nationally elevated road risk, attributed to the surge in travel during the holiday.\n:::\n\n### 8.3 Accidents by Day of Week\n\nInstead of just analysing based on individual day, accidents are split by weekday versus weekend.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_by_day <- accidents_bmr %>%\n  st_drop_geometry() %>%\n  mutate(day_type = if_else(day_of_week %in% c(\"Sat\", \"Sun\"), \"Weekend\", \"Weekday\")) %>%\n  count(day_of_week, day_type)\n\nplot_ly(accidents_by_day, x = ~day_of_week, y = ~n, color = ~day_type,\n        colors = c(\"Weekday\" = \"orange\", \"Weekend\" = \"seagreen\"), type = \"bar\") %>%\n  layout(title = \"Accidents by Day of Week\",\n         xaxis = list(title = \"Day of Week\"), yaxis = list(title = \"Number of Accidents\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-b85bf888dc62471906a9\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-b85bf888dc62471906a9\">{\"x\":{\"visdat\":{\"65f044a13b39\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"65f044a13b39\",\"attrs\":{\"65f044a13b39\":{\"x\":{},\"y\":{},\"color\":{},\"colors\":[\"orange\",\"seagreen\"],\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"bar\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"Accidents by Day of Week\",\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Day of Week\",\"type\":\"category\",\"categoryorder\":\"array\",\"categoryarray\":[\"Mon\",\"Tue\",\"Wed\",\"Thu\",\"Fri\",\"Sat\",\"Sun\"]},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Number of Accidents\"},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[\"Mon\",\"Tue\",\"Wed\",\"Thu\",\"Fri\"],\"y\":[500,455,472,529,595],\"type\":\"bar\",\"name\":\"Weekday\",\"marker\":{\"color\":\"rgba(255,165,0,1)\",\"line\":{\"color\":\"rgba(255,165,0,1)\"}},\"textfont\":{\"color\":\"rgba(255,165,0,1)\"},\"error_y\":{\"color\":\"rgba(255,165,0,1)\"},\"error_x\":{\"color\":\"rgba(255,165,0,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[\"Sat\",\"Sun\"],\"y\":[572,470],\"type\":\"bar\",\"name\":\"Weekend\",\"marker\":{\"color\":\"rgba(46,139,87,1)\",\"line\":{\"color\":\"rgba(46,139,87,1)\"}},\"textfont\":{\"color\":\"rgba(46,139,87,1)\"},\"error_y\":{\"color\":\"rgba(46,139,87,1)\"},\"error_x\":{\"color\":\"rgba(46,139,87,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\n- Weekday totals rise steadily across the week, from the lowest point on Tuesday to the highest point on Friday.\n- Between the two weekend days, Saturday records a noticeably higher total than Sunday.\n- Friday and Saturday together stand out as the two highest days overall, straddling the weekday to weekend transition. This may reflect increased travel for social or leisure purposes as the weekend begins.\n- Sunday's accident drop back toward weekday levels could reflect reduced travel activity as the weekend winds down.\n:::\n\n### 8.4 Accidents by Peak Period\n\nAccidents are examined by peak period: Morning Peak, Evening Peak, and Off-Peak.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_by_peak <- accidents_bmr %>%\n  st_drop_geometry() %>%\n  count(peak_period) %>%\n  mutate(\n    peak_period = factor(peak_period, levels = c(\"Morning Peak\", \"Evening Peak\", \"Off-Peak\")),\n    hours_in_period = case_when(\n      peak_period == \"Morning Peak\" ~ 2,\n      peak_period == \"Evening Peak\" ~ 3,\n      peak_period == \"Off-Peak\" ~ 19\n    ),\n    accidents_per_hour = n / hours_in_period\n  )\n\nplot_ly(accidents_by_peak, x = ~peak_period, y = ~accidents_per_hour, type = \"bar\",\n        marker = list(color = c(\"Morning Peak\" = \"orange\", \"Evening Peak\" = \"tomato\", \"Off-Peak\" = \"lightblue\")[as.character(accidents_by_peak$peak_period)])) %>%\n  layout(title = \"Average Accidents per Hour by Peak Period\",\n         xaxis = list(title = \"Peak Period\", categoryorder = \"array\", categoryarray = c(\"Morning Peak\", \"Evening Peak\", \"Off-Peak\")),\n         yaxis = list(title = \"Accidents per Hour\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-88fdd2a34d502a66744b\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-88fdd2a34d502a66744b\">{\"x\":{\"visdat\":{\"65f03e0cf78\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"65f03e0cf78\",\"attrs\":{\"65f03e0cf78\":{\"x\":{},\"y\":{},\"marker\":{\"color\":[\"tomato\",\"orange\",\"lightblue\"]},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"bar\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"Average Accidents per Hour by Peak Period\",\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Peak Period\",\"categoryorder\":\"array\",\"categoryarray\":[\"Morning Peak\",\"Evening Peak\",\"Off-Peak\"],\"type\":\"category\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Accidents per Hour\"},\"hovermode\":\"closest\",\"showlegend\":false},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[\"Evening Peak\",\"Morning Peak\",\"Off-Peak\"],\"y\":[168.66666666666666,171,144.47368421052633],\"marker\":{\"color\":[\"tomato\",\"orange\",\"lightblue\"],\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"type\":\"bar\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n::: callout-important\nMorning Peak, Evening Peak, and Off-Peak are unequal length periods: 2, 3, and 19 hours respectively. A raw count comparison across `peak_period` would favour Off-Peak simply because it covers more clock time, instead of carrying more risk per hour. Counts are therefore converted to an average per hour before comparison, so that the three periods are placed on equal footing.\n:::\n\n::: callout-note\n**Analysis:**\n\n- Morning Peak records the highest average accidents per hour among the three periods, narrowly ahead of Evening Peak.\n- Both Morning and Evening Peak records are well above Off-Peak. Off-Peak records the lowest average accidents per hour.\n:::\n\n### 8.5 Accidents by Presumed Cause\n\nThe presumed cause recorded for each accident is counted and ranked.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_bmr %>%\n  st_drop_geometry() %>%\n  count(presumed_cause, sort = TRUE) %>%\n  mutate(presumed_cause = fct_reorder(presumed_cause, n)) %>%\n  ggplot(aes(x = n, y = presumed_cause)) +\n  geom_col(fill = \"steelblue\") +\n  labs(title = \"Accidents by Presumed Cause\", x = \"Number of Accidents\", y = NULL)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\n- Speeding is the most common presumed cause, well ahead of every other category. It accounts for a substantially larger number of accidents than every other category combined.\n- All other causes account for comparatively few accidents each, with a long tail of rarely recorded categories.\n:::\n\n### 8.6 Accidents by Accident Type\n\nAccidents are broken down by accident type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_bmr %>%\n  st_drop_geometry() %>%\n  count(accident_type, sort = TRUE) %>%\n  mutate(accident_type = fct_reorder(accident_type, n)) %>%\n  ggplot(aes(x = n, y = accident_type)) +\n  geom_col(fill = \"steelblue\") +\n  labs(title = \"Accidents by Accident Type\", x = \"Number of Accidents\", y = NULL)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\n- Rear-end collision is the most common accident type, followed by rollover/fallen on straight road.\n- The remaining types account for a comparatively smaller number of accidents.\n:::\n\n### 8.7 Accidents by Vehicle Type\n\n`vehicle_type` contains a long tail of rare categories. Only the ten most frequent are shown.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_bmr %>%\n  st_drop_geometry() %>%\n  count(vehicle_type, sort = TRUE) %>%\n  slice_max(n, n = 10) %>%\n  mutate(vehicle_type = fct_reorder(vehicle_type, n)) %>%\n  ggplot(aes(x = n, y = vehicle_type)) +\n  geom_col(fill = \"steelblue\") +\n  labs(title = \"Top 10 Vehicle Types Involved in Accidents\", x = \"Number of Accidents\", y = NULL)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\n- Private/passenger car and 4-wheel pickup truck are the two most common vehicle types involved.\n- The remaining vehicle types account for a comparatively small share of the top ten.\n:::\n\n### 8.8 Accidents by Weather Condition\n\nThe weather condition recorded at the time of each accident is broken down by category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_bmr %>%\n  st_drop_geometry() %>%\n  count(weather_condition, sort = TRUE) %>%\n  mutate(weather_condition = fct_reorder(weather_condition, n)) %>%\n  ggplot(aes(x = n, y = weather_condition)) +\n  geom_col(fill = \"steelblue\") +\n  labs(title = \"Accidents by Weather Condition\", x = \"Number of Accidents\", y = NULL)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\n- The majority of accidents occurred under clear weather conditions.\n- Rainy conditions account for a much smaller share of accidents.\n:::\n\n### 8.9 Overall Severity\n\nTotal accidents, fatalities, injuries, and the count of accidents involving at least one fatality are summarised below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_bmr %>%\n  st_drop_geometry() %>%\n  summarise(\n    total_accidents = n(),\n    total_fatalities = sum(number_of_fatalities),\n    total_injuries = sum(number_of_injuries),\n    fatal_accidents = sum(number_of_fatalities > 0)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  total_accidents total_fatalities total_injuries fatal_accidents\n            <int>            <dbl>          <dbl>           <int>\n1            3593              176           2093             159\n```\n\n\n:::\n:::\n\n\n## 9 Spatial Point Pattern Analysis (SPPA)\n\nThis section applies spatial point pattern analysis (SPPA) using **spatstat** to quantify how road traffic accidents are distributed across the BMR, and to test whether the distribution departs from the Complete Spatial Randomness (CSR) hypothesis, which assumes that accidents occur independently and uniformly across the study area.\n\nThree methods are applied:\n\n1.  **First-order analysis:** Examine how accident intensity varies across the region, using kernel density estimation to identify areas of concentration\n\n2.  **Second-order analysis:** Use Ripley's G, F, K, and L functions to test whether accidents are more clustered, more regular, or consistent with CSR at varying distances\n\n3.  **Network-constrained analysis:** Account for accidents being restricted to the road network rather than free to occur anywhere in planar space\n\n### 9.1 Constructing the Point Pattern Objects\n\nBefore SPPA can begin, the `sf` objects prepared above are converted into `ppp` (point pattern) and `owin` (observation window) objects, so that they are in the formats **spatstat** works with.\n\nThe observation window is built first, from `adm2_bmr`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadm2_owin <- as.owin(adm2_bmr)\nadm2_owin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwindow: polygonal boundary\nenclosing rectangle: [565545.8, 743060.3] x [1468709.7, 1599777.2] units\n```\n\n\n:::\n:::\n\n\nThe point pattern is then built from `accidents_bmr`, using the above observation window:\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_ppp <- as.ppp(accidents_bmr, W = adm2_owin)\naccidents_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 3593 points\nMark variables: \n   acc_code incident_datetime province_en agency vehicle_type presumed_cause \naccident_type number_of_vehicles_involved number_of_fatalities \nnumber_of_injuries weather_condition road_description slope_description month \nmonth_label day_of_week day_of_year season peak_period songkran_dangerous_days\nwindow: polygonal boundary\nenclosing rectangle: [565545.8, 743060.3] x [1468709.7, 1599777.2] units\n```\n\n\n:::\n:::\n\n\nNext, the point pattern is checked for duplicated points, since accidents recorded at identical coordinates are treated differently by **spatstat** than by **sf**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(duplicated(accidents_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n::: callout-note\nSince no duplicated points are found, `rjitter()` will not be needed.\n:::\n\n`accidents_ppp` and `adm2`\\_owin are rescaled from metres to kilometres as this keeps the intensity and area readable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_ppp_km <- rescale(accidents_ppp, 1000, \"km\")\nadm2_owin_km <- rescale(adm2_owin, 1000, \"km\")\n```\n:::\n\n\nThe rescaled point pattern is plotted against its window, confirming the points fall within the study area:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(unmark(accidents_ppp_km), main = \"Road Accidents in the BMR (2022)\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-45-1.png){width=1152}\n:::\n:::\n\n\n### 9.2 First Order Spatial Point Pattern Analysis\n\nFirst-order analysis begins with kernel density estimation (KDE), which estimates how accident intensity, the expected number of accidents per unit area, varies continuously across the BMR. Unlike a count aggregated by district, KDE produces a smooth surface that does not depend on how the study area happens to be divided into administrative units.\n\n#### 9.2.1 Kernel Density Estimation (KDE)\n\nKDE's most consequential parameter is its bandwidth (`sigma` in **spatstat**), which controls how far each point's influence is smoothed. Too small produces a noisy surface; too large oversmooths and hides genuine concentration. Three automatic selectors, each using a different criterion, are computed and compared rather than fixing a value by inspection.\n\n**Diggle's method** minimises the mean-square error of the estimated intensity and tends to select a small bandwidth sensitive to fine-scale clustering:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_diggle <- bw.diggle(accidents_ppp_km)\nbw_diggle\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sigma \n0.06412305 \n```\n\n\n:::\n:::\n\n\n**The Cronie-van Lieshout method** is designed to directly minimise estimation error in the intensity function itself:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_cvl <- bw.CvL(accidents_ppp_km)\nbw_cvl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sigma \n28.622 \n```\n\n\n:::\n:::\n\n\n**Likelihood cross-validation** tends toward comparatively larger bandwidths that risk oversmoothing local detail:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_ppl <- bw.ppl(accidents_ppp_km)\nbw_ppl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    sigma \n0.9342669 \n```\n\n\n:::\n:::\n\n\nThe three values are compared directly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(diggle = bw_diggle, CvL = bw_cvl, ppl = bw_ppl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     diggle         CvL         ppl \n 0.06412305 28.62200060  0.93426689 \n```\n\n\n:::\n:::\n\n\nThe unusually large CvL value, 28.622km against 0.064km and 0.934km for the other two, is further checked.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(bw_cvl)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\nThe curve is flat between roughly 10 km and 28 km before rising sharply. However, the criterion barely distinguishes between bandwidths across that range. At 28.6 km, roughly a quarter of the BMR's extent (90 to 125 km), the result would also collapse local concentration into a single regional trend. For both reasons, `bw.CvL` is not the most appropriate.\n:::\n\nDensity surfaces are computed using both remaining bandwidths (`bw.diggle` and `bw.ppl`), for visual comparison before either is treated as final.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_diggle <- density(accidents_ppp_km, sigma = bw_diggle, edge = TRUE, kernel = \"gaussian\")\nkde_ppl <- density(accidents_ppp_km, sigma = bw_ppl, edge = TRUE, kernel = \"gaussian\")\n\npar(mfrow = c(1, 2))\nplot(kde_diggle, main = \"Diggle bandwidth\")\nplot(kde_ppl, main = \"ppl bandwidth\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-51-1.png){width=1152}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\nBoth surfaces trace the same underlying pattern despite using different bandwidths. This agreement is a useful check as it suggests that the pattern reflects real spatial concentration, not an artefact of one bandwidth choice. Diggle's bandwidth shows this pattern at finer resolution and will be used as the primary surface moving forward.\n:::\n\n#### 9.2.2 Quadrat Analysis\n\nQuadrat analysis complements KDE with a simpler, non-kernel method. The study area is divided into a grid of equal-sized cells, and the number of accidents in each cell is compared against what Complete Spatial Randomness would predict.\n\nThe grid resolution is chosen so that it matches the shape of the study area, and each cell has enough expected accidents for the chi-square test below to be valid; at least 5 per cell is a common rule of thumb. `adm2_owin`'s enclosing rectangle is approximately 177.5 km by 131.1 km, an aspect ratio of about 1.35, which is close to a 12 by 9 grid's ratio of 1.33.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqcount <- quadratcount(accidents_ppp_km, nx = 12, ny = 9)\n\nplot(unmark(accidents_ppp_km), pch = 20, cex = 0.4, main = \"Quadrat Counts of Road Accidents\")\nplot(qcount, add = TRUE, col = \"red\", cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\nThe variance to mean ratio (VMR) provides a quick diagnostic. A value close to 1 is consistent with CSR, above 1 suggests clustering, and below 1 suggests regularity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqcount_df <- as.data.frame(qcount)\nvmr <- var(qcount_df$Freq) / mean(qcount_df$Freq)\nvmr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 176.6295\n```\n\n\n:::\n:::\n\n\nA chi-square test of CSR is performed, using the same grid:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquadrat.test(accidents_ppp_km, nx = 12, ny = 9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test of CSR using quadrat counts\n\ndata:  accidents_ppp_km\nX2 = 10056, df = 83, p-value < 2.2e-16\nalternative hypothesis: two.sided\n\nQuadrats: 84 tiles (irregular windows)\n```\n\n\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\nVMR and the chi-square test answer different questions: VMR measures how large the departure from CSR is; the chi-square test measures whether that departure could be due to chance. With a sample this large, the chi-square test is almost always significant and the test alone would not show the effect is substantial. VMR fills this gap: at 176.6, where the value is significantly higher than 1 expected under CSR, it shows the clustering is genuinely large. The chi-square test confirms it is not due to chance. This agrees with the KDE surface, both methods point to the same conclusion.\n:::\n\n#### 9.2.3 KDE Comparison by Province\n\nThe region-wide KDE surface shows where accidents concentrate across the whole BMR, but not how that pattern differs between provinces. This section computes a separate density surface for each of the six BMR provinces, using each province's own boundary as the window.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_by_province <- list()\n\nfor (i in seq_along(bmr_provinces)) {\n  province_owin <- adm2_bmr %>%\n    filter(province_name == bmr_provinces_adm1[i]) %>%\n    as.owin() %>%\n    rescale(1000, \"km\")\n\n  province_ppp <- accidents_ppp_km[province_owin]\n  kde_by_province[[bmr_provinces[i]]] <- density(province_ppp, sigma = bw_diggle, edge = TRUE, kernel = \"gaussian\")\n}\n```\n:::\n\n\nThe six surfaces are plotted on a shared colour scale for direct comparison:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince_range <- range(sapply(kde_by_province, function(im) range(im$v, na.rm = TRUE)))\n\npar(mfrow = c(3, 2), mar = c(2, 2, 2, 4))\nfor (nm in names(kde_by_province)) {\n  plot(kde_by_province[[nm]], main = nm, axes = TRUE, box = TRUE)\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-56-1.png){width=1152}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\nAcross all six provinces, accidents cluster tightly along specific road corridors, appearing on each map as thin, bright lines.\n\n**Bangkok** and **Samut Prakan** show the highest peak intensities among the six provinces, with colour scales reaching approximately 170 and 250 respectively. In both cases, this intensity is concentrated along short, specific highway segments rather than distributed across the province. **Nakhon Pathom** shows the lowest peak intensity, with its colour scale reaching only about 10, and its hotspots appear comparatively scattered rather than concentrated on one corridor. **Nonthaburi** and **Pathum Thani** fall in between, with colour scales reaching approximately 44 and 50 respectively. For both provinces, hotspots concentrate toward the southern portion of the province, the area bordering Bangkok.\n:::\n\n### 9.3 Second-Order Spatial Point Pattern Analysis\n\nSecond-order SPPA analysis complements the first-order analysis by examining the arrangement of points relative to one another at varying distances, rather than counts within fixed cells or grid squares.\n\nFour methods are applied in this section: the Clark-Evans test, the G-function, the F-function, and the paired K- and L-functions, each testing the CSR hypothesis through nearest-neighbour or inter-point distances.\n\n#### 9.3.1 Nearest Neighbour Analysis: Clark-Evans Test\n\nThe Clark-Evans test compares the observed mean nearest-neighbour distance between accidents against the distance expected under Complete Spatial Randomness (CSR).\n\n- R = 1 is consistent with CSR: accidents are randomly distributed.\n- R < 1 indicates clustering: accidents lie closer together than CSR would predict.\n- R > 1 indicates regularity or dispersion: accidents are more evenly spaced than CSR would predict.\n\nThe test hypothesis:\n\n- **Null Hypothesis (H0):** Traffic accidents are randomly distributed across the BMR.\n- **Alternative Hypothesis (H1):** Traffic accidents are not randomly distributed across the BMR.\n\nThe hypothesis tests will use a 5% significance level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(accidents_ppp_km, \n                correction = \"cdf\", \n                alternative = \"clustered\", \n                nsim = 99, \n                method = \"MonteCarlo\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tCDF correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  accidents_ppp_km\nR = 0.17703, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n`correction = \"cdf\"` is used since `adm2_owin_km` is an irregular polygon rather than a rectangle. It handles edge effects without requiring a rectangular window.\n:::\n\n::: callout-note\n**Analysis:**\n\n- R = 0.177, which is significantly below 1, indicates accidents lie much closer to their nearest neighbour than CSR would predict: strong evidence of clustering.\n- p-value = 0.01, reject the null hypothesis since p-value falls below the 0.05 significance level.\n\nRoad accidents in the BMR are strongly clustered rather than randomly distributed, agreeing with the KDE surface and the quadrat test's VMR of 176.6.\n:::\n\n#### 9.3.2 G-Function\n\nThe G-function estimates G(r), the probability that the distance from a typical accident to its nearest neighbouring accident is at most r. Unlike the Clark-Evans test, which reduces the whole pattern to a single R statistic, G(r) shows how that clustering behaves across a range of distances rather than just at one summary value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_accidents <- Gest(accidents_ppp_km, correction = \"km\")\nplot(G_accidents, legendpos = \"right\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\nA Monte Carlo envelope tests whether the observed G-function departs from CSR.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_accidents.csr <- envelope(accidents_ppp_km, Gest, \n                            correction = \"km\", \n                            nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(G_accidents.csr, legendpos = \"topright\", legendargs = list(cex = 0.8))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\n- The observed G-function rises sharply within the first 0.1km, reaching approximately 0.70, while the CSR line only reaches around 0.05 at the same distance. By r = 0.5km, the observed curve flattens near 0.90, significantly above CSR. \n- The Monte Carlo envelope confirms this is not due to chance. The observed line sits entirely above the grey simulation envelope across the full range (0 to 0.5km).\n- This means road accidents in BMR are strongly clustered at short distances.\n:::\n\n#### 9.3.3 F-Function\n\nThe F-function estimates F(r), the probability that the distance from a random location (not an accident) to its nearest accident is at most r. F reads in the opposite direction from G: a lower observed F-function indicates clustering, since clustered points leave larger empty gaps between them for F to measure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_accidents <- Fest(accidents_ppp_km, correction = \"km\")\nplot(F_accidents, legendpos = \"topleft\", legendargs = list(cex = 0.8))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n:::\n\n\nA Monte Carlo envelope tests whether the observed F-function departs from CSR.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_accidents.csr <- envelope(accidents_ppp_km, Fest, \n                            correction = \"km\", \n                            nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(F_accidents.csr, legendpos = \"topleft\", legendargs = list(cex = 0.8))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-61-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\n- The observed F-function sits below the CSR line across the entire distance range. At r = 1km, observed F is only around 0.15 whereas CSR is around 0.60.\n- The Monte Carlo envelope confirms this is not due to chance. The observed line sits entirely below the grey simulation envelope across the whole range. \n- Since a lower-than-expected F-function indicates clustering, this means a randomly chosen location in the BMR takes much longer to reach its nearest accident than CSR would predict, consistent with accidents leaving large empty gaps between clusters rather than being spread evenly across the region.\n:::\n\n#### 9.3.4 K-Function and L-Function\n\nFor K-function, K(r) estimates the expected number of accidents found within distance r of a typical accident, compared to what CSR would predict. A higher-than-CSR K(r) indicates clustering.\n\n::: callout-note\nInstead of spatstat's default, `rmax = 1` limits the K- and L-function estimates to 1km, since the G- and F-function results above already show clustering concentrated within roughly 0.1 to 0.5km.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nK_accidents <- Kest(accidents_ppp_km, correction = \"Ripley\", rmax = 1)\nplot(K_accidents)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-62-1.png){width=672}\n:::\n:::\n\n\nK(r) grows quickly with distance under CSR, producing a steep curve that makes subtle departures difficult to discern visually. The L-function rescales K into a version that grows steadily and predictably under CSR, so any departure from a straight line stands out clearly instead of being hidden inside a curve. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_accidents <- Lest(accidents_ppp_km, correction = \"Ripley\", rmax = 1)\nplot(L_accidents, . - r ~ r, legendpos = \"bottomright\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n:::\n\n\nA single Monte Carlo envelope, run on the L-function, tests both K and L-function together, since L is just a clearer view of the same underlying K result. `global = TRUE` is used, testing whether the observed line departs from CSR anywhere across the full distance range instead of one fixed distance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_accidents.csr <- envelope(accidents_ppp_km, Lest, correction = \"Ripley\", rmax = 1, nsim = 99, global = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(L_accidents.csr, . - r ~ r, legendpos = \"right\", legendargs = list(cex = 0.8))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-64-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\n- The observed K-function lies well above the CSR line across the entire range (0 to 1km). The L-function confirms this after removing the quadratic CSR trend.\n- The Monte Carlo envelope confirms this is statistically significant, as the observed line remains outside the envelope across the entire range. Therefore, the null hypothesis of CSR is rejected.\n\nOverall, the results agree with Clark-Evans, G-function, and F-function.\n:::\n\n## 10 Spatio-Temporal Point Pattern Analysis\n\n### 10.1 Spatio-Temporal KDE by Month\n\nKDE and quadrat analysis above addressed how accident intensity varies across space. This section focuses on the temporal portion, examining whether accident intensity varies across the year. The point pattern is split by month, and a separate density surface is computed for each.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccidents_ppp_month <- accidents_ppp_km\nmarks(accidents_ppp_month) <- marks(accidents_ppp_km)$month\n\nst_kde <- spattemp.density(accidents_ppp_month)\nsummary(st_kde)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 4.8825 (spatial)\n  lambda = 0.0285 (temporal)\n\nNo. of observations\n  3593 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [565.5458, 743.0603] x [1468.71, 1599.777]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [7.546022e-35, 0.002849939]\n```\n\n\n:::\n:::\n\n\nTwelve monthly slices are plotted on a shared colour scale for direct comparison across the year:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(4, 3), mar = c(2, 2, 2, 2))\nfor (i in 1:12) {\n  plot(st_kde, i,\n       override.par = FALSE,\n       fix.range = TRUE,\n       main = paste(\"Month\", i))\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-66-1.png){width=960}\n:::\n:::\n\n\n::: callout-note\n**Analysis:**\n\n**Month 1** shows a moderately widespread hotspot concentrated in the central BMR, with some diffusion into surrounding areas.\n\n**Months 2 to 7** show generally lower intensity, with hotspots more contained.\n\n**Months 8 to 11** show accident density concentrated around Bangkok increasing in both intensity and spatial extent, with the branching pattern along major roads becoming more pronounced.\n\n**Month 12** shows the highest density of the year, concentrated in central BMR, likely due to increased travel during the year-end and holiday period. This also coincides with the start of Thailand's New Year \"Seven Dangerous Days\" period, 29 December 2022 to 4 January 2023, of which 29 to 31 December falls within the study period. 317 deaths were recorded nationwide [GT Rider, citing Thailand's Road Safety Centre, 2023](https://www.thegtrider.com/thailand-2022-2023-new-year-road-traffic-report-deaths.htm).\n:::\n\n## Reference\n",
    "supporting": [
      "Take-home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.12.1/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}